Md file
zinka22/Selenium-cource pull request #11
Opened 2024-05-16 09:57 UTC by zinka22

Тут сделала md файл и ссылку на него в одном py файле, перенести в папку не смогла (не видит)

и зацепилась не оттуда

2024-05-16 12:19 UTC, Cliffart44 requested changes
Для начала стоит убрать все лишние коммиты с помощью [перебазирования в интерактивном режиме](https://www.atlassian.com/ru/git/tutorials/rewriting-history/git-rebase). Так как в настоящее время в ветке 33 коммита, команда для Git Bash будет выглядеть следующим образом: `git rebase -i HEAD~33`. Затем откроется текстовый редактор со следующим содержимым:

<details><summary>/Selenium-cource/.git/rebase-merge/git-rebase-todo</summary>
<p>

```bash
pick 26aac1e Add files via upload
pick f479128 first commit with 1 idea of deleting duplications
pick aa69c05 deleted file, which should not be in this commit
pick 7f0ba61 moved closing logic, changed group of imports, variable link was not deleted
pick b5b4118 replace code duplication with helpers module add helpers module to folder upload_file_from_pc
pick 96291c6 plus one task, the other tasks will be commit by folders
pick 722cf8c add link to readme
pick c424735 formatted
pick fe1d38d delete variable
pick 7e6cadb push switch after rebase
pick 2300ecc Add files via upload
pick 68a00bb first commit with 1 idea of deleting duplications
pick cde8602 deleted file, which should not be in this commit
pick 7b19dab try to rebase 4
pick 8013a62 delete/add spases as in main
pick 56f6245 no 4 spaces
pick a0d1b2b test save for testin link to the file
pick 0fc7b1f add slashes in link
pick 8e3f3f9 delete dot
pick a0b57fd add quotes check result in git
pick 44a74c9 change tasks file
pick d59414a last try and then go sleep
pick 7edb33c add text as in an article
pick b8d8309 commit idea with directory
pick c61a3b0 commit +1  idea with directory
pick a5d7db8 Revert "no 4 spaces"
pick 76c838a add file and link
pick d101d54 add task for #9 and link to task in 9
pick a7879bb new name of link
pick 64849eb add # to md file
pick 08c9c93 add # to md file
pick 54d3764 add link to readme file
pick 53531c9 add link to readme file

# Rebase 3c2e973..53531c9 onto 3c2e973 (33 commands)
#
# Commands:
# p, pick <commit> = use commit
# r, reword <commit> = use commit, but edit the commit message
# e, edit <commit> = use commit, but stop for amending
# s, squash <commit> = use commit, but meld into previous commit
# f, fixup [-C | -c] <commit> = like "squash" but keep only the previous
#                    commit's log message, unless -C is used, in which case
#                    keep only this commit's message; -c is same as -C but
#                    opens the editor
# x, exec <command> = run command (the rest of the line) using shell
# b, break = stop here (continue rebase later with 'git rebase --continue')
# d, drop <commit> = remove commit
# l, label <label> = label current HEAD with a name
# t, reset <label> = reset HEAD to a label
# m, merge [-C <commit> | -c <commit>] <label> [# <oneline>]
#         create a merge commit using the original merge commit's
#         message (or the oneline, if no original merge commit was
#         specified); use -c <commit> to reword the commit message
# u, update-ref <ref> = track a placeholder for the <ref> to be updated
#                       to this position in the new commits. The <ref> is
#                       updated at the end of the rebase
#
# These lines can be re-ordered; they are executed from top to bottom.
#
# If you remove a line here THAT COMMIT WILL BE LOST.
#
# However, if you remove everything, the rebase will be aborted.
#
```

</p>
</details>

Далее, согласно описанию, `pick` напротив всех ненужных коммитов нужно заменить на `d`, затем выйти из редактора с сохранением изменений. Содержание коммитов можно смотреть, к примеру, [здесь](https://github.com/zinka22/Selenium-cource/pull/11/commits). Наконец, когда останутся только нужные коммиты, стоит перебазировать ветку относительно `main`.

2024-05-19 20:48 UTC, zinka22 commented
> Для начала стоит убрать все лишние коммиты с помощью [перебазирования в интерактивном режиме](https://www.atlassian.com/ru/git/tutorials/rewriting-history/git-rebase). Так как в настоящее время в ветке 33 коммита, команда для Git Bash будет выглядеть следующим образом: `git rebase -i HEAD~33`. Затем откроется текстовый редактор со следующим содержимым:
> 
> ~/Selenium-cource/.git/rebase-merge/git-rebase-todo
> Далее, согласно описанию, `pick` напротив всех ненужных коммитов нужно заменить на `d`, затем выйти из редактора с сохранением изменений. Содержание коммитов можно смотреть, к примеру, [здесь](https://github.com/zinka22/Selenium-cource/pull/11/commits) (или через [локальный клиент](https://confluence.atlassian.com/get-started-with-sourcetree)). Наконец, когда останутся только нужные коммиты, стоит перебазировать ветку относительно `main`.

прочитала первое предложение и пошла делать, взяла статью и пошла делать (т.е. дальше не прочитала и git rebase -i HEAD~33 не взяла). Редактор предложил 22 коммита, нужных там не было (все 22 это попытки сделать ссылку).

К слову я ее так и не сделала. Относительная ссылка точно работает в файле md  и не получается в файле py.
Итого:
1) делала git rebase --interactive <base>, 22 комита убрала, git сказал, что все app to date, но в удаленном репозитории есть еще лишних 12 комитов. 
Почему: на локальной машине "main выше main origin на 12 комитов. До этого дельта была в 17, перед rebase md_file делала rebase main и main origin. Rebase написал, что все доделал и все совместил - 12 осталось. Непонятно пока.
Т.е. есть разница между main в удаленном и на локальной машине на 12 комитов, тут как раз эти 12 комитов повисли. Нужно будет повторить для main и md еще раз.
2) не могу побороть ссылки. Тыкаюсь в одно и то же, кликабельности в py файле добиться не могу. Искать другой способ или твой по ссылке в py файле тоже должен работать https://github.blog/2013-01-31-relative-links-in-markup-files/ ?

2024-05-20 10:02 UTC, Cliffart44 commented
Итак, по порядку: насколько понял, к настоящему моменту здесь должен остаться вообще один коммит. Первые 12 можно удалить как описано в https://github.com/zinka22/Selenium-cource/pull/11#pullrequestreview-2060574409. А оставшиеся два... Для удаления единственной строки не требуется отдельный коммит — можно исправить предыдущий с помощью

`git reset` 2a6458d05b7e339ae898a83f51165097feae4188

и
```bash
git commit -a --amend --no-edit
```

В итоге получится [вот что](https://github.com/zinka22/Selenium-cource/compare/md-file-clone?expand=1) 🙂
И да, этот PR получается уже больше для практики по Git (что тоже хорошо).

---
А что касается ссылок — в https://github.com/zinka22/Selenium-cource/issues/10#issuecomment-2110509908 выразился явно неточно. Сейчас исправил:

![image](https://github.com/zinka22/Selenium-cource/assets/64852774/eb5bf72b-675f-415f-813a-225c62b38ec1)

Согласно ссылке на инструкцию в блоге GitHub [оттуда](https://github.com/zinka22/Selenium-cource/issues/10#issuecomment-2110509908),

> We show rendered markup in several places on GitHub, most notably including a
project’s main README on the Repository page itself.
>
> Starting today, GitHub supports relative links in markup files. Now you can
link directly between different documentation files, whether you view the
documentation on GitHub itself, or locally, using a different markup renderer.

Речь идёт о "most notably including a
project’s main README on the Repository page itself", то есть об относительных ссылках на md-файлы из README.md.

"GitHub supports relative links in markup files" — GitHub поддерживает относительные ссылки __в файлах разметки__".

И далее речь о "you can link directly between different *__documentation files__*". Нет речи о том, что ссылки на py-файлы будут работать в обе стороны. Не `.md <=> .py`, а только `.md => .py`. 

---
Итак, во втором коммите можно сделать вот что:
1. В tasks/for_test_link.md добавить относительную ссылку на py-файл (и сам файл назвать соответственно).
2. В switch_to_window.py в начале просто написать что-то типа "Задание содержится в tasks/for_test_link.md"
3. В README.md прописать заголовок задания и затем две ссылки: на полный текст задания и на реализацию.

2024-05-20 20:20 UTC, zinka22 commented
> Итак, по порядку: насколько понял, к настоящему моменту здесь должен остаться вообще один коммит. Первые 12 можно удалить как описано в [#11 (review)](https://github.com/zinka22/Selenium-cource/pull/11#pullrequestreview-2060574409). А оставшиеся два... Для удаления единственной строки не требуется отдельный коммит — можно исправить предыдущий с помощью
> 
> `git reset` [2a6458d](https://github.com/zinka22/Selenium-cource/commit/2a6458d05b7e339ae898a83f51165097feae4188)
> 
> и
> 
> ```shell
> git commit -a --amend --no-edit
> ```
> 
> В итоге получится [вот что](https://github.com/zinka22/Selenium-cource/compare/md-file-clone?expand=1) 🙂 И да, этот PR получается уже больше для практики по Git (что тоже хорошо).
> 
вот тут сделала, вторую часть пока нет

2024-05-21 03:58 UTC, Cliffart44 commented
> вот тут сделала, вторую часть пока нет

Также при необходимости можно исправить сообщение последнего коммита: `git commit - -amend -m "Новое сообщение"`. Либо с помощью уже известного интерактивного перебазирования 😉

2024-05-21 19:44 UTC, zinka22 commented on README.md
локально у меня так красиво смотрится..
сижу пока не понимаю, почему в Git не так, грустно.

![image](https://github.com/zinka22/Selenium-cource/assets/108293161/bff30776-2955-4ef7-b8f0-cdd9da0d4f60)

2024-05-22 06:54 UTC, Cliffart44 commented on README.md
> локально у меня так красиво смотрится.. сижу пока не понимаю, почему в Git не так, грустно. Остается надеяться, что тут и не должно красиво отображаться

Ты имеешь в виду GitHub? Просто Git — система контроля версий, и там хранится всё именно так, как ты поместила. А [в GitHub](https://github.com/zinka22/Selenium-cource/tree/md_file) всё отображается таким же образом, как и на скриншоте.

2024-05-22 07:27 UTC, Cliffart44 requested changes
В целом всё выглядит хорошо, ты уловила суть! 🙂
Сейчас открою дополнительный pull reqest #12 — если там всё понравится, то и этот затем можно будет слить.

2024-05-22 15:57 UTC, zinka22 commented on README.md
да, верное замечание

Имела ввиду github

2024-05-24 03:17 UTC, Cliffart44 approved these changes
Хорошо, и теперь для каждого последующего задания делай, пожалуйста, отдельный pull request — теперь последовательно смогу сопоставлять задачу и реализацию.

2024-05-24 03:21 UTC, merged