Expected_conditions
zinka22/Selenium-cource pull request #13
Opened 2024-05-25 18:05 UTC by zinka22

задача+текстовый файл с заданием

2024-05-25 18:49 UTC, Cliffart44 requested changes
Не добавлены ссылки в README.md, и также открой, пожалуйста, хотя бы один PR как писал тут https://github.com/zinka22/Selenium-cource/pull/11#pullrequestreview-2075573876 — речь об уже имеющихся заданиях.

2024-05-25 18:51 UTC, Cliffart44 commented on tasks/expected_conditions.md
> +Отправьте его в качестве ответа на это задание.
И ещё добавь, пожалуйста, пустую строку в конце файла 🙂

2024-05-25 20:35 UTC, zinka22 commented on tasks/expected_conditions.md
> +Отправьте его в качестве ответа на это задание.
и название поменяю, копировала с другого файла, забыла шапку поменять. сделаю

2024-05-25 21:00 UTC, zinka22 commented
> и также открой, пожалуйста, хотя бы один PR как писал тут [#11 (review)](https://github.com/zinka22/Selenium-cource/pull/11#pullrequestreview-2075573876) — речь об уже имеющихся заданиях.

не поняла что сделать и не понимаю как погуглить

сделала ветку, в ней задача, решение задачи и ссылка в Readme (добавлю)
когда в #11 писал про PR, думала, вот так делать и так ок

поясни, пожалуйста, сделаю, как надо.

2024-05-25 21:42 UTC, zinka22 commented on tasks/expected_conditions.md
> +Отправьте его в качестве ответа на это задание.
ранее говорил, что для "убрать строчку" можно не делать отдельно коммит, а вернуться на предыдущий через git reset

я сейчас пока так делала, потеряла твой последний комментарий (если смотреть в комит, в беседе он остался)

Есть критичное ограничение, когда так делать нельзя? (то что твой комент потеряю не сообразила. это не специально было)

2024-05-25 21:43 UTC, zinka22 commented on tasks/expected_conditions.md
> +Отправьте его в качестве ответа на это задание.
ранее говорил, что для "убрать строчку" можно не делать отдельно коммит, а вернуться на предыдущий через git reset

я сейчас пока так делала, потеряла твой последний комментарий (если смотреть в комит, в беседе он остался)

Есть критичное ограничение, когда так делать нельзя? (то что твой комент потеряю не сообразила. это не специально было)

2024-05-26 16:23 UTC, Cliffart44 commented
> поясни, пожалуйста, сделаю, как надо.

Создал #15 — уточняй там дальше, если требуется.

2024-05-26 16:38 UTC, Cliffart44 requested changes
В целом по логике проблем не заметил, но полноценно ревью смогу завершить на ноутбуке (сейчас смотрел со 📱).

2024-05-26 16:38 UTC, Cliffart44 commented on README.md
> +| [Настройка ожиданий](tasks/expected_conditions.md) | [expected_conditions](expected_conditions.py) |
Есть предложение сортировать строки в таблице по именам файлов. Что думаешь?

2024-05-26 16:38 UTC, Cliffart44 commented on expected_conditions.py
> +from selenium.webdriver.support import expected_conditions as EC
Тут твой PyCharm не обращает внимание на регистр объявляемой переменной? 🙂

2024-05-26 16:38 UTC, Cliffart44 commented on expected_conditions.py
> +    element_x_int = int(browser.find_element(By.ID, "input_value").text)
Тут при чтении не понимаю, что за такой таинственный элемент Икс в числовом виде 🤷🏻‍♂️ (хотя соприкасался с этим ранее — вот почему важно подбирать "говорящие" имена переменным 😉)

2024-05-26 16:38 UTC, Cliffart44 commented on tasks/expected_conditions.md
> +expected_conditions.
Почему в пункте 5 точка стоит, а в предыдущих четырёх нет? 🙂 Мелочь, конечно, но везде хорошо поддерживать консистентность (или единообразие): пункт списка — это обычное предложение, а значит, оно должно начинаться с заглавной буквы и иметь точку в конце (мой учитель по русскому языку будет доволен, что я написал это 😄).

2024-05-26 17:31 UTC, zinka22 commented on README.md
> +| [Настройка ожиданий](tasks/expected_conditions.md) | [expected_conditions](expected_conditions.py) |
да ок. Автоматического пути нет для REDME (или не нашла)
Если так, по мере поступления строк буду сортировать

2024-05-26 17:35 UTC, zinka22 commented on expected_conditions.py
> +from selenium.webdriver.support import expected_conditions as EC
![image](https://github.com/zinka22/Selenium-cource/assets/108293161/c6ce45da-dcbe-44f5-907d-3b846bc234d5)
если вот тут, то нет

но, скорее всего, я ему сказала не обращать внимание. Когда делала задачу, находила такой формат обозначения, заглавными
вот например как тут, в первом сверху блоке кода https://selenium-python.readthedocs.io/waits.html

И в уроке так же писали. Нужно понизить?

2024-05-26 17:37 UTC, zinka22 commented on expected_conditions.py
> +    element_x_int = int(browser.find_element(By.ID, "input_value").text)
подумаю о переименовании и рефакторинге. На странице он элемент х и рядом число, вот так 
![image](https://github.com/zinka22/Selenium-cource/assets/108293161/d0ea67be-73b4-4d79-abdc-8e7cfc64c40d)

2024-05-26 17:48 UTC, zinka22 commented on tasks/expected_conditions.md
> +expected_conditions.
тут копировала задание с задачи с сайта. Они неправильно написали пункт списка. 
Изменю.

А вообще, если придираться, оформление списка идет аналогично следующему:
1) в предыдущем предложении ставим двоеточие;
2) между элементами списка точку с запятой;
3) каждый новый элемент списка начинается с маленькой буквы;
4) в конце последнего пункта ставим точку.
Например, документ ГОСТА по оформлению диссертации, список оформлен аналогично указанному выше
![image](https://github.com/zinka22/Selenium-cource/assets/108293161/8906a6d4-4b7e-440f-b78a-ffd7b6508ca3)

Душность закончилась) Долго работала с бывшим редактором Мнемозины (издательство специализируется на учебниках).

2024-05-27 06:49 UTC, Cliffart44 commented on tasks/expected_conditions.md
> +Отправьте его в качестве ответа на это задание.
> ранее говорил, что для "убрать строчку" можно не делать отдельно коммит, а вернуться на предыдущий через git reset
> 
> я сейчас пока так делала, потеряла твой последний комментарий (если смотреть в комит, в беседе он остался)
> 
> Есть критичное ограничение, когда так делать нельзя? (то что твой комент потеряю не сообразила. это не специально было)

Да, только `git reset` здесь избыточен — `git commit -a --amend --no-edit` просто вносит изменение в последний имеющийся коммит. Так не стоит делать в ветках, над которыми работают несколько человек, потому что у них не будет нормально работать `git pull`. Когда над веткой работаешь сама — и работаешь как самой удобно.

2024-05-27 07:03 UTC, Cliffart44 commented on expected_conditions.py
> +from selenium.webdriver.support import expected_conditions as EC
![image](https://github.com/zinka22/Selenium-cource/assets/64852774/48664f60-d430-4ab2-9ebb-4ead279d6190)

Не знаю, почему это иногда игнорируют, но сам стараюсь учитывать такое. На мой взгляд, `ec` вместо `EC` никаких проблем не создаёт 🙂

Ну и в Alt+6 вот что:
![image](https://github.com/zinka22/Selenium-cource/assets/64852774/49f2b45b-7e44-4290-bd91-5940b4fc48e4)

Второе black сам исправляет — примени.

2024-05-27 07:17 UTC, Cliffart44 commented on expected_conditions.py
> +    element_x_int = int(browser.find_element(By.ID, "input_value").text)
Согласно [теории](https://www.yaklass.ru/p/matematika/5-klass/naturalnye-chisla-13442/formuly-uravneniia-uproshchenie-vyrazhenii-13788/re-46999386-c771-4ac9-a3e4-9bda4bd9cab2), «Уравнение — это выражение, в котором есть знак «равно» и латинская буква, которая обозначает переменную и значение которой надо найти. Корень уравнения — это число, которое можно подставить вместо буквы и при вычислении получить равенство». Отсюда первое, что приходит на ум,
```python
    equation_root = browser.find_element(By.ID, "input_value").text
    math_result = helpers.solve_math_expression_for_captcha(equation_root)
```

Кстати, необходымые преобразования уместно поручить функции-помощнику, и тогда в solve_math_expression_for_captcha будет
```python
    return str(log(abs(12 * sin(int(x)))))
```

2024-05-27 07:34 UTC, Cliffart44 commented on tasks/expected_conditions.md
> +expected_conditions.
Хорошо, это будет консистентно! 🙂

<details><summary>Больше о пунктуации</summary>
<p>

---
Элементы списка могут оканчиваться запятой, точкой с запятой или точкой.
- запятая ставится, если пункт списка состоит из нескольких слов без знаков препинания.
- точка с запятой ставится, если элемент перечня состоит из сложных словосочетаний и присутствуют знаки препинания.
- точка ставится, если пункт списка представляет собой целое законченное предложение, или если для обозначения элемента использованы буква или цифра с точкой.

[Источник](https://advegital.com/academy/glossary/oformlenie-markirovannykh-i-numerovannykh-spiskov.html#:~:text=%D0%97%D0%9D%D0%90%D0%9A%D0%98%20%D0%9F%D0%A0%D0%95%D0%9F%D0%98%D0%9D%D0%90%D0%9D%D0%98%D0%AF%20%D0%92,%D1%86%D0%B8%D1%84%D1%80%D0%B0%20%D1%81%20%D1%82%D0%BE%D1%87%D0%BA%D0%BE%D0%B9.)

---
Ещё [отсюда](https://infogra.ru/typography/11-pravil-oformleniya-spiskov-i-perechnej):
«...после римских и арабских (без скобок) цифр по правилам русского языка ставится точка, а после точки, как все мы помним с начальной школы, начинается новое предложение, которое пишется с заглавной буквы». И там же пример 7 о том, что части перечня могут представлять собой отдельные ­предложения.

---
Однако, ты оформляй так, как самой удобнее читать — но единообразно 😉

</p>
</details>

2024-05-27 10:11 UTC, zinka22 commented on expected_conditions.py
> +from selenium.webdriver.support import expected_conditions as EC
сделала ec, применила black

2024-05-27 10:32 UTC, zinka22 commented on expected_conditions.py
> +    element_x_int = int(browser.find_element(By.ID, "input_value").text)
Поняла. Переименование элемента х и изменение ф-ии в helpers сделаю отдельно

2024-05-27 10:34 UTC, zinka22 commented on tasks/expected_conditions.md
> +expected_conditions.
принято

2024-05-27 11:28 UTC, Cliffart44 commented on expected_conditions.py
> +    element_x_int = int(browser.find_element(By.ID, "input_value").text)
> Поняла. Переименование элемента х и изменение ф-ии в helpers сделаю отдельно, когда этот файл попадет в главную

В таком случае создай, пожалуйста, два ✌ issue на этот счёт и приложи их сюда.

2024-05-27 11:47 UTC, Cliffart44 requested changes
Сейчас всё посмотрел.

2024-05-27 11:47 UTC, Cliffart44 commented on README.md
> +| [Настройка ожиданий](tasks/expected_conditions.md) | [expected_conditions](expected_conditions.py) |
Посмотри, пожалуйста, пункт 2 в #12 для README.md и тоже сделай.

2024-05-27 11:47 UTC, Cliffart44 commented on tasks/expected_conditions.md
> +
Посмотри, пожалуйста, пункт 2 в #12 для switch_to_window.md и тоже сделай. Ну и тут лишняя пустая строка в конце файла 😆

2024-05-27 11:47 UTC, Cliffart44 commented on expected_conditions.py
> +
В switch_to_window.py тут одна пустая строка. Как будешь делать — одну или две? 🙂

2024-05-27 11:47 UTC, Cliffart44 commented on expected_conditions.py
> +# Задание содержится в tasks/expected_conditions.md
https://github.com/zinka22/Selenium-cource/pull/17#discussion_r1615652488

2024-05-27 11:47 UTC, Cliffart44 commented on expected_conditions.py
> +    check_for_correct_price = WebDriverWait(browser, 12).until(
Согласно условию, "ожидание нужно установить не меньше 12 секунд". Если говорить о стабильности работы тестов, то тут будет хорошо дать какой-то запас и ждать, скажем, 15 секунд.

2024-05-27 17:37 UTC, zinka22 commented on expected_conditions.py
> +    element_x_int = int(browser.find_element(By.ID, "input_value").text)
#19 и #20

2024-05-27 17:49 UTC, zinka22 commented on README.md
> +| [Настройка ожиданий](tasks/expected_conditions.md) | [expected_conditions](expected_conditions.py) |
сделала ок

2024-05-27 17:53 UTC, zinka22 commented on tasks/expected_conditions.md
> +
сделала ок (нет, не получилось)

2024-05-27 17:54 UTC, zinka22 commented on expected_conditions.py
> +
одну строку после задания, поправила

2024-05-27 17:58 UTC, Cliffart44 commented on expected_conditions.py
> +    element_x_int = int(browser.find_element(By.ID, "input_value").text)
Теперь эти моменты не забудутся.

2024-05-27 18:17 UTC, zinka22 commented on expected_conditions.py
> +# Задание содержится в tasks/expected_conditions.md
сделала папку, перенесла expected_conditions в папку (изменились относительные ссылки у README и в задаче)

2024-05-27 18:19 UTC, zinka22 commented on expected_conditions.py
> +    check_for_correct_price = WebDriverWait(browser, 12).until(
ок, сделала 15

2024-05-27 18:29 UTC, zinka22 commented on tasks/expected_conditions.md
> +
чистенько все делала, пока не пошла тут исправлять

было 2 пустые строки, убрала. 
отправила в удаленный, поняла, что нет пустой строки.

сохранить правку из пустой строки нельзя, вернулась на последний комит сделала пустую строку-ее тут нет. Сдаюсь(

2024-05-27 18:31 UTC, Cliffart44 commented on README.md
> +| [Настройка ожиданий](tasks/expected_conditions.md) | [expected_conditions](expected_conditions.py) |
Уверена?

2024-05-27 18:53 UTC, Cliffart44 commented on tasks/expected_conditions.md
> +
Добавление строки — тоже правка и Git её видит. Сейчас тут всё в порядке.

2024-05-27 18:57 UTC, Cliffart44 approved these changes

2024-05-27 18:58 UTC, merged