Оформление теста в стиле unittest
zinka22/Selenium-cource pull request #14
Opened 2024-05-25 21:26 UTC by zinka22

Здесь добавила текст задачи, решение задачи, ссылку в README.

Т.к. в задаче переиспользуется результат решения другой задачи, для лучшего понимания условия, после абсолютной ссылки (на старую задачу) в файле с заданием добавила относительную ссылку.

1) tasks/unittest_style.md - файл с текстом задания
2) unittest_style.py - решение задания
3) README.md тут две новые ссылки на задачи (unittest_style.md и check_registration_form.md)
4)) tasks/check_registration_form.md вспомогательная задача: ссылка на решение используется в unittest_style.md, относительная ссылка на задание добавлена в помощь к абсолютной ссылке на задание
4) check_registration_form.py тут дописала комментарий, что есть файл с текстом задачи
5) check_registration_with_bugz.py тут дописала комментарий, что есть файл с текстом задачи

2024-05-28 07:10 UTC, Cliffart44 requested changes
Pull request в целом нуждается в обновлении согласно текущему состоянию main.
Также при этом проверь, пожалуйста, что он содержит реализацию только одной задачи. Если есть что-то зависимое, то лучше создать отдельный pull request и ссылаться на него как на приоритетный относительно текущего или последующий относительно текущего же.

2024-05-28 18:46 UTC, zinka22 commented
> Pull request в целом нуждается в обновлении согласно текущему состоянию main.

тут нужно перебазирование сделать, верно поняла?

2024-05-29 04:38 UTC, Cliffart44 commented
> > Pull request в целом нуждается в обновлении согласно текущему состоянию main.
> 
> тут нужно перебазирование сделать, верно поняла?
> 
> (проверять нечего, запросить ревью тыкнула зря)
> 
> 

Да, но не только 😉

2024-06-04 18:12 UTC, zinka22 commented
> > > Pull request в целом нуждается в обновлении согласно текущему состоянию main.
> > 
> > 
> > тут нужно перебазирование сделать, верно поняла?
> 
> Да, но не только 😉

сделала

и еще настройку с black, до этого пропустила комент 
у меня вот так

<details><summary>настройки в pycharm, black</summary>
<p>

![image](https://github.com/zinka22/Selenium-cource/assets/108293161/5ff86f33-46bb-4364-aff7-b9c4340e6825)


</p>
</details>

2024-06-05 08:15 UTC, Cliffart44 requested changes
И стоит обновить описание pull request-а, если правильно понял: https://github.com/zinka22/Selenium-cource/pull/14#issue-2317255506.

2024-06-05 08:15 UTC, Cliffart44 commented on tasks/unittest_style.md
> +### оформляем тесты в стиле unittest
https://github.com/zinka22/Selenium-cource/pull/17#discussion_r1618267851

```suggestion
### Оформление тестов в стиле unittest
```

2024-06-05 08:15 UTC, Cliffart44 commented on tasks/unittest_style.md
> +1) возьмите тесты из [check_registration_form](check_registration_form.py) и
```suggestion
1) возьмите тесты из [check_registration_form](../check_registration_form.py) и
```

2024-06-05 08:15 UTC, Cliffart44 commented on tasks/unittest_style.md
> +   [check_registration_with_bugz](check_registration_with_bugz.py);
```suggestion
   [check_registration_with_bugs](../check_registration_with_bugz.py);
```

2024-06-05 08:15 UTC, Cliffart44 commented on tasks/unittest_style.md
> +2) cоздайте новый файл;
```suggestion
2) создайте новый файл;
```

2024-06-05 08:15 UTC, Cliffart44 commented on tasks/unittest_style.md
> +3) cоздайте в нем класс с тестами, который должен наследоваться от unittest.TestCase по аналогии с предыдущим шагом;
```suggestion
3) создайте в нем класс с тестами, который должен наследоваться от `unittest.TestCase` по аналогии с предыдущим шагом;
```

2024-06-05 08:15 UTC, Cliffart44 commented on solutions/unittest_style.py
> +        try:
```suggestion
```

2024-06-05 08:15 UTC, Cliffart44 commented on solutions/unittest_style.py
> +            input1 = browser.find_element(By.CLASS_NAME, "form-control.first")
Это же поле для ввода имени? Почему бы тогда переменную не назвать соответственно?

2024-06-05 08:15 UTC, Cliffart44 commented on solutions/unittest_style.py
> +            button = browser.find_element(By.CSS_SELECTOR, "button.btn")
А что это за кнопка? Что делает? Почему бы тогда переменную не назвать соответственно? 😉

2024-06-05 08:15 UTC, Cliffart44 commented on solutions/unittest_style.py
> +            sleep(1)
#23

2024-06-05 08:15 UTC, Cliffart44 commented on solutions/unittest_style.py
> +            welcome_text_elt = browser.find_element(By.TAG_NAME, "h1")
А что такое "elt"? [English Language Teaching](https://www.oxfordlearnersdictionaries.com/definition/english/elt)?

2024-06-05 08:15 UTC, Cliffart44 commented on solutions/unittest_style.py
> +    def test_check_registration_with_bugz(self):
```suggestion
    def test_check_registration_with_bugs(self):
```

2024-06-05 08:15 UTC, Cliffart44 commented on solutions/unittest_style.py
> +        try:
```suggestion
```

2024-06-05 08:15 UTC, Cliffart44 commented on solutions/unittest_style.py
> +
```suggestion
```

2024-06-05 10:42 UTC, zinka22 commented
> И стоит обновить описание pull request-а, если правильно понял: [#14 (comment)](https://github.com/zinka22/Selenium-cource/pull/14#issue-2317255506).

убрала информацию про добавление +1 задачи и изменении py файлов check_registration_form.py и check_registration_form_with_bugz.py (они в задаче нужны как уже реализованный код, тут нет необходимости добавлять задание и описание в py файл)

2024-06-05 10:48 UTC, zinka22 commented on tasks/unittest_style.md
> +2) cоздайте новый файл;
> 

не пойму что тут было

латинская первая с?

2024-06-05 10:52 UTC, zinka22 commented on solutions/unittest_style.py
> +        try:
> 

try убрать, finally ставить. Почему?

2024-06-05 10:58 UTC, Cliffart44 commented on solutions/unittest_style.py
> +        try:
Обе конструкции убрать, конечно же 🙂

2024-06-05 11:06 UTC, zinka22 commented on solutions/unittest_style.py
> +            welcome_text_elt = browser.find_element(By.TAG_NAME, "h1")
не мое название. первые занятия, там задание типа "все скопируй в середине поменяй, чтобы вот так работало". Вернула пропущенные буквы

<details><summary>elt еще может быть вот таким</summary>
<p>

![image](https://github.com/zinka22/Selenium-cource/assets/108293161/9dc43e71-b7c7-49f1-8e4b-4b3e40468e91)

</p>
</details>

2024-06-05 11:14 UTC, Cliffart44 commented on solutions/unittest_style.py
> +            welcome_text_elt = browser.find_element(By.TAG_NAME, "h1")
Поэтому чаще всего аббревиатуры лучше не использовать. `welcome_text_elt` и `welcome_text_element` не особо отличаются по длине, плюс можно сократить до `welcome_element` — и тогда вообще короче получается.

2024-06-05 16:56 UTC, zinka22 commented on solutions/unittest_style.py
> +            sleep(1)
сделала как в #23

2024-06-05 16:56 UTC, zinka22 commented on solutions/unittest_style.py
> +            input1 = browser.find_element(By.CLASS_NAME, "form-control.first")
переименовала +2 аналогичных input

2024-06-05 17:04 UTC, zinka22 commented on solutions/unittest_style.py
> +            button = browser.find_element(By.CSS_SELECTOR, "button.btn")
сделала

2024-06-06 07:50 UTC, Cliffart44 requested changes

2024-06-06 07:50 UTC, Cliffart44 commented on solutions/unittest_style.py
> +        browser.quit()
Это стоит поместить в [tearDown()](https://docs.python.org/3/library/unittest.html#unittest.TestCase.tearDown). Сможешь объяснить почему?

2024-06-06 07:50 UTC, Cliffart44 commented on tasks/unittest_style.md
> +6) оформите финальные проверки в тестах в стиле unittest, например, используя проверочный метод assertEqual;
```suggestion
6) оформите финальные проверки в тестах в стиле unittest, например, используя проверочный метод `assertEqual`;
```

2024-06-06 07:50 UTC, Cliffart44 commented on tasks/unittest_style.md
> +Это всё для иллюстрации того, что unittest выполнит тесты и обобщит результаты даже при наличии неожиданного исключения.
```suggestion
10) обратите внимание, что по задумке должно выбрасываться исключение `NoSuchElementException` во втором тесте.
11) Если вы использовали конструкцию `try/except`, здесь нужно запустить тест без неё. Ловить исключения не надо
    (во всяком случае, здесь)! Это всё для иллюстрации того, что unittest выполнит тесты и обобщит результаты даже при
    наличии неожиданного исключения.
```

2024-06-06 13:21 UTC, zinka22 commented on solutions/unittest_style.py
> +        browser.quit()
tearDown() может включать множество действий по очистке (не только закрытие браузера, но и удаление тестовых данных или сброс конфигураций) - более универсальный для очистки, гарантирует, что при каждом новом тесте начинаем с чистого состояния

почитала, изменила, чтобы вызывать tearDown(): работать стало после добавления setUp вместе с tearDown(). Одним коммитом, если что можно будет вернуться обратно

2024-06-06 13:50 UTC, Cliffart44 requested changes

2024-06-06 13:50 UTC, Cliffart44 commented on solutions/unittest_style.py
> +    def tearDown(self):
Расположить лучше рядом с setUp ([пример](https://realpython.com/python-unittest/#:~:text=%3D%20Stack()-,def%20tearDown(self)%3A,-del%20self.)).

2024-06-06 13:50 UTC, Cliffart44 commented on solutions/unittest_style.py
> +        browser.quit()
Всё верно: в прошлой реализации при падении теста оставалось открытое окно браузера, поскольку закрывающий его код не выполнялся. Также можно обойтись и без setUp, но тут он к месту, так даже удобнее.

2024-06-06 13:50 UTC, Cliffart44 commented on tasks/unittest_style.md
> +Это всё для иллюстрации того, что unittest выполнит тесты и обобщит результаты даже при наличии неожиданного исключения.
И тут тоже актуально https://github.com/zinka22/Selenium-cource/pull/26#pullrequestreview-2101244767.

2024-06-06 17:48 UTC, zinka22 commented on solutions/unittest_style.py
> +    def tearDown(self):
сделала, прочитала

2024-06-06 19:12 UTC, Cliffart44 approved these changes
Остался один вопрос — вынесу отдельно.

2024-06-06 19:13 UTC, merged