Перенос файла с заданием: doc_confirm_alert
zinka22/Selenium-cource pull request #16
Opened 2024-05-26 17:08 UTC by zinka22

1) сделала md файл с заданием confirm_alert
2) в README для задачи убрала абсолютную ссылку, добавила относительную ссылку на md file и ссылку на py

2024-05-27 07:56 UTC, Cliffart44 requested changes

2024-05-27 07:56 UTC, Cliffart44 commented on README.md
> +| [Принимаем alert](tasks/confirm_alert.md) | [confirm_alert](confirm_alert.py) |
[Аналогично этому](https://github.com/zinka22/Selenium-cource/pull/13/files#r1615259880).

---
Также, согласно [уже упомянутому](https://github.com/zinka22/Selenium-cource/pull/13/files#r1615603313) [источнику](https://infogra.ru/typography/11-pravil-oformleniya-spiskov-i-perechnej), должна быть «согласованность элементов списка. При составлении перечней следует обязательно обращать внимание на то, чтобы начальные слова каждого элемента списка были согласованы между собой в роде, числе и падеже». То есть «Принимаем alert» было бы уместно при наличии «Переходим на новую вкладку». Присутствует же «Переход на новую вкладку».

---
Зачем говорю об этом? Это формирует образ мышления. В коде консистентность очень важна, и если придерживаться её везде, то и код будет получаться более качественным.

2024-05-27 07:56 UTC, Cliffart44 commented on tasks/confirm_alert.md
> +1) Открыть страницу http://suninjuly.github.io/alert_accept.html
[Аналогично этому](https://github.com/zinka22/Selenium-cource/pull/13/files#r1615261948).

2024-05-27 07:56 UTC, Cliffart44 commented on confirm_alert.py
> +# Задание содержится в tasks/confirm_alert.md
[Аналогично этому](https://github.com/zinka22/Selenium-cource/issues/15#issuecomment-2132293439).

2024-05-27 10:59 UTC, zinka22 commented on README.md
> +| [Принимаем alert](tasks/confirm_alert.md) | [confirm_alert](confirm_alert.py) |
тут для задания switch_to_window сделала название задания "переходим..", т.к. то же название присутствует в md файле с задачей (switch_to_window.md) - добавила окончание в название задачи.

В файле switch_to_window.md список оформлен неединообразно, тут не правила. Если тут можно, поправлю тут. Иначе отдельно PR сделаю на список

2024-05-27 10:59 UTC, zinka22 commented on tasks/confirm_alert.md
> +1) Открыть страницу http://suninjuly.github.io/alert_accept.html
поправила

2024-05-27 11:00 UTC, zinka22 commented on confirm_alert.py
> +# Задание содержится в tasks/confirm_alert.md
сделала rebase относительно doc_folder_to_py_files

2024-05-27 11:24 UTC, Cliffart44 commented on tasks/confirm_alert.md
> +1) Открыть страницу http://suninjuly.github.io/alert_accept.html
А точно изменения отправила в удалённый репозиторий?

2024-05-27 11:25 UTC, Cliffart44 commented on confirm_alert.py
> +# Задание содержится в tasks/confirm_alert.md
https://github.com/zinka22/Selenium-cource/pull/17#discussion_r1615652488

2024-05-27 11:56 UTC, Cliffart44 commented on README.md
> +| [Принимаем alert](tasks/confirm_alert.md) | [confirm_alert](confirm_alert.py) |
Если делать https://github.com/zinka22/Selenium-cource/pull/17#discussion_r1615652488, то в #17 можно и доработать switch_to_window.md, потому что тогда это будет PR рефакторинга этого конкретного упражнения и все связанные с ним изменения будут уместны.

2024-05-27 12:57 UTC, zinka22 commented on tasks/confirm_alert.md
> +1) Открыть страницу http://suninjuly.github.io/alert_accept.html
нет, на ребеис застряла, все поломала локально. бросила и пошла работать)

2024-05-27 13:02 UTC, zinka22 commented on confirm_alert.py
> +# Задание содержится в tasks/confirm_alert.md
до конца не поняла ни первоначальный ни последующий комментарий
_________
вводная:
задание распознала так: вот текст в шапке реализации, при этом я предлагал перенести реализацию в папку с py файлами, перенеси и эту

сслыка с номером 15 ведет сюда 
![image](https://github.com/zinka22/Selenium-cource/assets/108293161/af6daab2-3f81-499b-bb85-181416738193)

после дописал ссылку с номером 17
_______________________________________

а вот теперь вопрос: тут мне нужна папка и в ней не нужны файлы. Наверное нужно в #17 сделать комит с папкой, а потом комит с рефакторингом файла switch в папку.

И тогда смогу переставить head на комит с папкой и потом в эту папку в рамках 16 положить.

2024-05-27 13:05 UTC, zinka22 commented on README.md
> +| [Принимаем alert](tasks/confirm_alert.md) | [confirm_alert](confirm_alert.py) |
на удаленный не отправила, локально вернусь к "началу" и эту правку тут делать не буду

2024-05-27 13:49 UTC, Cliffart44 commented on README.md
> +| [Принимаем alert](tasks/confirm_alert.md) | [confirm_alert](confirm_alert.py) |
Правильно понял, что ты в #17 приведёшь «Переход на новую вкладку» к «Переходим на новую вкладку»?

2024-05-27 13:54 UTC, Cliffart44 commented on confirm_alert.py
> +# Задание содержится в tasks/confirm_alert.md
Ничего не мешает просто создать здесь нужную структуру (да и незачем без необходимости создавать взаимосвязи между несколькими PR). А принцип исполнения должен быть ровно тот же, что и в #17.

2024-05-28 18:02 UTC, zinka22 commented on README.md
> +| [Принимаем alert](tasks/confirm_alert.md) | [confirm_alert](confirm_alert.py) |
в #17 сделала

2024-05-29 06:57 UTC, Cliffart44 commented on README.md
> +| [Принимаем alert](tasks/confirm_alert.md) | [confirm_alert](confirm_alert.py) |
Теперь ждём https://github.com/zinka22/Selenium-cource/pull/17#discussion_r1618267851 😆

2024-05-30 04:40 UTC, zinka22 commented on README.md
> +| [Принимаем alert](tasks/confirm_alert.md) | [confirm_alert](confirm_alert.py) |
итого в ветке три строки задач, добавила 1 строку с заданием alert

первое слово названия задачи - существительное, решено и сделано тут https://github.com/zinka22/Selenium-cource/pull/17#discussion_r1619763552, далее делаю единообразно

2024-05-30 04:41 UTC, zinka22 commented on tasks/confirm_alert.md
> +1) Открыть страницу http://suninjuly.github.io/alert_accept.html
сделала с маленькой буквы, точка с запятой в конце строки; в конце последнего пункта списка точка

2024-05-30 04:42 UTC, zinka22 commented on confirm_alert.py
> +# Задание содержится в tasks/confirm_alert.md
добавила папку, в папку перенесла confirm_alert.py

2024-05-30 06:50 UTC, Cliffart44 requested changes

2024-05-30 06:50 UTC, Cliffart44 commented on README.md
```suggestion
```

2024-05-30 06:50 UTC, Cliffart44 commented on README.md
>  |:-----------------------------------------------------:|:-------------------------------------------------------:|
https://github.com/zinka22/Selenium-cource/pull/13#discussion_r1615926161

2024-05-30 06:50 UTC, Cliffart44 commented on README.md
> +| [Подтверждение действия в alert](tasks/confirm_alert.md) | [confirm_alert](solutions/confirm_alert.py) |
https://github.com/zinka22/Selenium-cource/pull/13#discussion_r1615259880

2024-06-02 07:26 UTC, zinka22 commented on README.md
>  |:-----------------------------------------------------:|:-------------------------------------------------------:|
отформатировала
сделала [настройку на редактирование](https://www.jetbrains.com/help/pycharm/reformat-and-rearrange-code.html#reformat-on-save) при сохранении. У меня вот так
<details><summary>настройки в pycharm</summary>
<p>

![image](https://github.com/zinka22/Selenium-cource/assets/108293161/a348b7a9-361d-494a-885a-bf79479f9161)


</p>
</details>

2024-06-02 07:31 UTC, zinka22 commented on README.md
> +| [Подтверждение действия в alert](tasks/confirm_alert.md) | [confirm_alert](solutions/confirm_alert.py) |
сделала, руками

если есть настройка и не нашла - напиши

2024-06-02 15:48 UTC, Cliffart44 commented on README.md
> +| [Подтверждение действия в alert](tasks/confirm_alert.md) | [confirm_alert](solutions/confirm_alert.py) |
Не уверен, что автоматически тут возможно быстро сделать такое 🤷‍♀️

2024-06-02 15:55 UTC, Cliffart44 commented on README.md
> +| [Подтверждение действия в alert](tasks/confirm_alert.md) |       [confirm_alert](solutions/confirm_alert.py)       |
Так если https://github.com/zinka22/Selenium-cource/pull/16#discussion_r1619977827, то эта строка должна быть 5-й, ведь
> A
> B
> ⚠️ __C__
> D
> ⚠️ __E__
...

2024-06-02 15:55 UTC, Cliffart44 commented on README.md
>  |:-----------------------------------------------------:|:-------------------------------------------------------:|
Да, отлично, здесь же и black включить можно — выполни `python -m pip install black` в терминале сначала.

2024-06-02 16:01 UTC, Cliffart44 requested changes
И добавился конфликт после #17.

2024-06-04 03:06 UTC, zinka22 commented on README.md
> +| [Подтверждение действия в alert](tasks/confirm_alert.md) |       [confirm_alert](solutions/confirm_alert.py)       |
изменила

2024-06-04 03:08 UTC, zinka22 commented
> И добавился конфликт после #17.

поправила

2024-06-04 07:43 UTC, Cliffart44 requested changes

2024-06-04 07:43 UTC, Cliffart44 commented on README.md
>  | [Переход на новую вкладку](tasks/switch_to_window.md) |    [switch_to_window](solutions/switch_to_window.py)    |
```suggestion
|  [Переход на новую вкладку](tasks/switch_to_window.md)   |    [switch_to_window](solutions/switch_to_window.py)    |
```

2024-06-04 07:46 UTC, Cliffart44 approved these changes

2024-06-04 07:47 UTC, merged