Перенос Py файлов в папку, аналогично tasks
zinka22/Selenium-cource pull request #17
Opened 2024-05-26 17:24 UTC by zinka22

1)сделала папку solutions
2)перенесла py файлы в папку solutions

2024-05-27 08:11 UTC, Cliffart44 requested changes
Предложения не являются критичными, но так будет логичнее и удобнее.

2024-05-27 08:11 UTC, Cliffart44 commented on solutions/upload_file_from_pc/upload_file_from_pc.py
> +from solutions import helpers
Так в helpers же нет решений как таковых — предлагаю оставить его как есть.

2024-05-27 08:11 UTC, Cliffart44 commented on README.md
> +| [Переход на новую вкладку](tasks/switch_to_window.md) | [switch_to_window](solutions/switch_to_window.py) |
В этом PR предлагаю переместить только этот файл. Остальные можно перемещать в дальнейших PR-ах наподобие #16.

2024-05-27 19:07 UTC, zinka22 commented on solutions/upload_file_from_pc/upload_file_from_pc.py
> +from solutions import helpers
ок, перенесла обратно в корень

2024-05-27 19:16 UTC, zinka22 commented on README.md
> +| [Переход на новую вкладку](tasks/switch_to_window.md) | [switch_to_window](solutions/switch_to_window.py) |
оставила в папке с решениями только switch_to_window, остальные вынесла обратно

2024-05-28 07:03 UTC, Cliffart44 requested changes
- [x] Стоит уточнить заголовок pull request-а.
- [x] Нужно разрешить конфликты.

2024-05-28 07:03 UTC, Cliffart44 commented on tasks/switch_to_window.md
>  ### Переход на новую вкладку
https://github.com/zinka22/Selenium-cource/pull/16#discussion_r1615950974

2024-05-28 07:03 UTC, Cliffart44 commented on README.md
> +| [Переход на новую вкладку](tasks/switch_to_window.md) | [switch_to_window](solutions/switch_to_window.py) |
https://github.com/zinka22/Selenium-cource/pull/16#discussion_r1616080555

2024-05-28 18:13 UTC, zinka22 commented
> * [x]  Стоит уточнить заголовок pull request-а.
> * [ ]  Нужно разрешить конфликты.

конфликты: или не поняла как "закрепить" разрешение после разрешения в гит; или в конце нужно делать когда объединять с main

2024-05-28 18:19 UTC, zinka22 commented on tasks/switch_to_window.md
>  ### Переход на новую вкладку
тут - переходИМ, а в 13 получилось "настройка"

1)+1 PR?
2) поправить комитом при добавлении в таблицу другой задачи просто отдельным комитом

2024-05-28 18:26 UTC, zinka22 commented on README.md
> +| [Переход на новую вкладку](tasks/switch_to_window.md) | [switch_to_window](solutions/switch_to_window.py) |
сделала

2024-05-29 04:36 UTC, Cliffart44 commented
> > * [x]  Стоит уточнить заголовок pull request-а.
> > * [ ]  Нужно разрешить конфликты.
> 
> конфликты: или не поняла как "закрепить" разрешение после разрешения в гитхаб; или в конце нужно делать когда объединять с main

Сделать коммит 🙂

2024-05-29 06:23 UTC, Cliffart44 commented on tasks/switch_to_window.md
>  ### Переход на новую вкладку
На мой взгляд, проще все названия привести к [начальной форме существительных](https://www.yaklass.ru/p/russky-yazik/3-klass/chast-rechi-imia-sushchestvitelnoe-423440/nachalnaia-forma-sushchestvitelnykh-rod-sushchestvitelnykh-408484/re-39b49258-455b-4b5b-bf11-cbcd8289fc7e): "Переход...", "Приём...", "Настройка..." (к слову, в #18 тоже именно так сейчас сделано).

Можно, конечно, привести и к "что делаем?" ("Переходим...", "Принимаем...", "Настраиваем..."), но это даже не [начальная форма глагола](https://www.yaklass.ru/p/russky-yazik/10-klass/razdel-morfologii-samostoiatelnye-chasti-rechi-10908/glagol-10923/re-6d6ceb0a-f5cf-4ed1-992a-f3c8f86ca0c4).

Если брать первый вариант, то тут остаётся только структуру файлов обновить и вид списка.
Если второй, то да, для expected_conditions нужен будет отдельный PR с исправлением.

Так что определись окончательно с этим и вперёд 😉

2024-05-29 06:26 UTC, Cliffart44 commented on README.md
> +| [Переход на новую вкладку](tasks/switch_to_window.md) | [switch_to_window](solutions/switch_to_window.py) |
https://github.com/zinka22/Selenium-cource/pull/17#discussion_r1618267851

2024-05-30 02:49 UTC, zinka22 commented on tasks/switch_to_window.md
>  ### Переход на новую вкладку
сделала "переход", первое слово будет существительным

2024-05-30 02:51 UTC, zinka22 commented on README.md
> +| [Переход на новую вкладку](tasks/switch_to_window.md) | [switch_to_window](solutions/switch_to_window.py) |
с https://github.com/zinka22/Selenium-cource/pull/17#discussion_r1619763552 сделала одним комитом

2024-05-30 02:52 UTC, zinka22 commented
> > > * [x]   Стоит уточнить заголовок pull request-а.
> > > * [ ]   Нужно разрешить конфликты.
> > 
> > 
> > конфликты: или не поняла как "закрепить" разрешение после разрешения в гитхаб; или в конце нужно делать когда объединять с main
> 
> Сделать коммит 🙂

тут сделала

2024-05-30 05:47 UTC, Cliffart44 requested changes

2024-05-30 05:47 UTC, Cliffart44 commented on tasks/switch_to_window.md
> +## Задание к [switch_to_window](../solutions/switch_to_window.py)
Ещё нужно сделать что в #15 указано 🙂

<details><summary>Screenshot</summary>
<p>

![Снимок экрана 2024-05-30 094619](https://github.com/zinka22/Selenium-cource/assets/64852774/ef81127f-ceb6-454f-a1ff-f6351f60c155)


</p>
</details>

2024-06-02 06:34 UTC, zinka22 commented on tasks/switch_to_window.md
> +## Задание к [switch_to_window](../solutions/switch_to_window.py)
невнимательность

сделала

2024-06-02 15:40 UTC, Cliffart44 approved these changes

2024-06-02 15:40 UTC, merged