Задача: запуск тестов в Pytest
zinka22/Selenium-cource pull request #18
Opened 2024-05-26 20:01 UTC by zinka22

тут добавила:
1) задачу из курса, текст
2) реализацию задания, только запуск тестов, ничего в ранее написанных скриптах не меняла
3) ссылку в README.MD

2024-05-28 07:20 UTC, Cliffart44 requested changes
И аналогично https://github.com/zinka22/Selenium-cource/pull/14#pullrequestreview-2081935959.

2024-05-28 07:20 UTC, Cliffart44 commented on pytest_style.py
> +        sleep(1)
Теперь, когда ты знаешь #13, давай не использовать прямые sleep — лучше добавь ожидание чего-то конкретного.

<details><summary>Да, и ещё...</summary>
<p>

![Лучше сделать меньше комментариев](https://habrastorage.org/r/w1560/getpro/habr/upload_files/ae3/cfe/196/ae3cfe196f9347d971a1ca2bf34ca394.png)

</p>
</details>

2024-05-28 07:20 UTC, Cliffart44 commented on tasks/pytest_style.md
> +Попробуйте запустить ваши тесты из урока 3.2 ([check_registration_form](../check_registration_form.py),
Оказывается, у уроков есть номера? Почему бы тогда не указывать их в README.md тоже?

2024-05-28 07:20 UTC, Cliffart44 commented on pytest_style.py
> +    browser = None
Насколько понял, тут дублируется код двух предыдущих упражнений?
Если так, то почему бы просто не импортировать их сюда и не вызывать в две строки?

2024-05-28 18:57 UTC, zinka22 commented on tasks/pytest_style.md
> +Попробуйте запустить ваши тесты из урока 3.2 ([check_registration_form](../check_registration_form.py),
там получится не линейная нумерация. Например, у двух задач модуля 3.2 получаться номера 3.2.4 и 3.2.13
![image](https://github.com/zinka22/Selenium-cource/assets/108293161/8c1a84fd-0f10-45bb-8408-f8f1bd38a693)
так что скорее нет. 

если нужно, добавлю

2024-05-29 06:06 UTC, Cliffart44 commented on tasks/pytest_style.md
> +Попробуйте запустить ваши тесты из урока 3.2 ([check_registration_form](../check_registration_form.py),
В таком случае проще тут не упоминать нумерацию, а просто оставить ссылки на задачи.

2024-05-29 06:53 UTC, Cliffart44 requested changes
Ну и конфликты...

2024-05-29 06:53 UTC, Cliffart44 commented on README.md
> +| [Вывод PyTest](tasks/pytest_style.md) | [pytest_style](pytest_style.py)|
https://github.com/zinka22/Selenium-cource/pull/13#discussion_r1615926161

2024-05-29 06:53 UTC, Cliffart44 commented on pytest_style.py
> +
```suggestion
```

2024-05-29 06:53 UTC, Cliffart44 commented on requirements.txt
> +pytest~=8.2.1
```suggestion
pytest~=8.2.1

```

2024-05-29 06:53 UTC, Cliffart44 commented on pytest_style.py
> +# Задание содержится в tasks/pytest_style.md
Почему файл задания лежит тут?

2024-05-29 06:53 UTC, Cliffart44 commented on pytest_style.py
> +    result = subprocess.run(["python", "check_registration_form.py"])
Уже гораздо лучше, чем было, но у меня не запустилось нормально. Возможно, будет лучше сделать немного иначе — попробую сам сначала.

<details><summary>Details</summary>
<p>

```bash
=========================================================================== test session starts ===========================================================================
platform win32 -- Python 3.12.3, pytest-8.2.1, pluggy-1.5.0
rootdir: C:\Users\Artjom\PycharmProjects\Selenium-cource
collected 2 items                                                                                                                                                          

pytest_style.py FF                                                                                                                                                   [100%]

================================================================================ FAILURES =================================================================================
___________________________________________________________________ test_check_registration_form_link1 ____________________________________________________________________

    def test_check_registration_form_link1():
        result = subprocess.run(["python", "check_registration_form.py"])

        if result.returncode != 0:
>           pytest.fail()
E           Failed

pytest_style.py:13: Failed
-------------------------------------------------------------------------- Captured stderr call --------------------------------------------------------------------------- 
Traceback (most recent call last):
  File "C:\Users\Artjom\PycharmProjects\Selenium-cource\check_registration_form.py", line 3, in <module>
    from selenium.webdriver.common.by import By
ModuleNotFoundError: No module named 'selenium'
___________________________________________________________________ test_check_registration_form_link2 ____________________________________________________________________ 

    def test_check_registration_form_link2():
        result = subprocess.run(["python", "check_registration_with_bugz.py"])

>           pytest.fail()
E           Failed

pytest_style.py:20: Failed
-------------------------------------------------------------------------- Captured stderr call --------------------------------------------------------------------------- 
Traceback (most recent call last):
  File "C:\Users\Artjom\PycharmProjects\Selenium-cource\check_registration_with_bugz.py", line 3, in <module>
    from selenium.webdriver.common.by import By
ModuleNotFoundError: No module named 'selenium'
========================================================================= short test summary info ========================================================================= 
FAILED pytest_style.py::test_check_registration_form_link1 - Failed
FAILED pytest_style.py::test_check_registration_form_link2 - Failed
============================================================================ 2 failed in 0.35s ============================================================================ 
```

</p>
</details>

2024-05-29 06:53 UTC, Cliffart44 commented on pytest_style.py
> +def test_check_registration_form_link1():
```suggestion
def test_check_registration_form():
```

2024-05-29 06:53 UTC, Cliffart44 commented on pytest_style.py
> +def test_check_registration_form_link2():
```suggestion
def test_check_registration_with_bugs():
```

2024-05-29 06:53 UTC, Cliffart44 commented on tasks/pytest_style.md
> +###  вывод PyTest
```suggestion
###  Вывод pytest
```

На [официальном сайте](https://docs.pytest.org/en/stable/) пишется именно так.

2024-05-29 06:53 UTC, Cliffart44 commented on tasks/pytest_style.md
> +
https://github.com/zinka22/Selenium-cource/pull/13#discussion_r1615928263

2024-06-02 08:03 UTC, zinka22 commented on README.md
> +| [Вывод PyTest](tasks/pytest_style.md) | [pytest_style](pytest_style.py)|
отформатировала
вот тут настройку сделала https://github.com/zinka22/Selenium-cource/pull/16#discussion_r1623345066, в действии проверена в том же PR

2024-06-02 08:06 UTC, zinka22 commented on pytest_style.py
> +# Задание содержится в tasks/pytest_style.md
Уточни, пожалуйста, задачу переноса в tasks. Думала план такой: каждое новое задание с кодом идет вместе со своим заданием в tasks. 
Старые задачи переношу в tasks отдельным PR,

2024-06-02 08:37 UTC, zinka22 commented on tasks/pytest_style.md
> +###  вывод PyTest
![image](https://github.com/zinka22/Selenium-cource/assets/108293161/620c951a-de8e-4e26-b5cd-9a42db7bee78)

2024-06-02 08:40 UTC, zinka22 commented on pytest_style.py
> +    browser = None
тут сделала вызов из другого файла, пока не одобрено

2024-06-02 08:41 UTC, zinka22 commented on tasks/pytest_style.md
> +Попробуйте запустить ваши тесты из урока 3.2 ([check_registration_form](../check_registration_form.py),
убрала нумерацию, оставила только ссылку

2024-06-02 08:55 UTC, zinka22 commented on tasks/pytest_style.md
> +
отформатировала
вот тут настройку сделала https://github.com/zinka22/Selenium-cource/pull/16#discussion_r1623345066, в действии проверена в том же PR

2024-06-02 09:50 UTC, zinka22 commented on pytest_style.py
> +        sleep(1)
сделаю отдельным PR

2024-06-02 09:53 UTC, zinka22 commented
> Ну и конфликты...

решила, подтвердила

2024-06-02 15:20 UTC, Cliffart44 requested changes
Посмотри, пожалуйста, этот комментарий.

2024-06-02 15:20 UTC, Cliffart44 commented on pytest_style.py
> +# Задание содержится в tasks/pytest_style.md
Всё верно, и образец того, что где лежит можно посмотреть в уже слитом [#13](https://github.com/zinka22/Selenium-cource/pull/13/files) 🙂

2024-06-02 15:20 UTC, Cliffart44 commented on README.md
> +|         [Вывод pytest](tasks/pytest_style.md)         |     [pytest_style](pytest_style.py)     |
https://github.com/zinka22/Selenium-cource/pull/13#discussion_r1615926161

2024-06-02 15:20 UTC, Cliffart44 commented on pytest_style.py
> +    result = subprocess.run(["python", "check_registration_form.py"])
Посмотри, пожалуйста, #21 на этот счёт.

2024-06-02 15:20 UTC, Cliffart44 commented on requirements.txt
> +pytest~=8.2.1
Смотрю, здесь сортировка по алфавиту. Может, стоит не нарушать её? 🙂

2024-06-02 15:28 UTC, Cliffart44 commented on tasks/pytest_style.md
> +###  вывод PyTest
Согласно документации [GitHub](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request),
> Before you submit your review, your line comments are pending and only visible to you. You can edit pending comments anytime before you submit your review.

Ну и [больше информации](https://g.co/gemini/share/39878a4a0705) об этом ещё 😏

2024-06-02 15:30 UTC, Cliffart44 commented on tasks/pytest_style.md
> +с помощью PyTest. В выводе найдите последнюю строку, скопируйте её и отправьте в это задание. Отправьте текст, который
Кстати, тут тоже актуально https://github.com/zinka22/Selenium-cource/pull/18#discussion_r1618298338, в принципе.

2024-06-02 16:19 UTC, Cliffart44 commented on README.md
> +| [Вывод PyTest](tasks/pytest_style.md) | [pytest_style](pytest_style.py)|
Тут почему-то неровно 🤷‍♀️(https://github.com/zinka22/Selenium-cource/pull/18#discussion_r1623481589)

2024-06-02 16:20 UTC, Cliffart44 commented on pytest_style.py
> +    browser = None
И, опять же, #21 на этот счёт.

2024-06-02 16:21 UTC, Cliffart44 commented on pytest_style.py
> +        sleep(1)
Тогда нужна Issue на этот счёт — жду 🙂

2024-06-04 03:13 UTC, zinka22 commented on pytest_style.py
> +        sleep(1)
#22

2024-06-04 03:20 UTC, zinka22 commented on pytest_style.py
> +# Задание содержится в tasks/pytest_style.md
если правильно поняла:

- [ ] задание в папке tasks
- [ ] реализация в папке solutions
- [ ] в задании ссылка на реализацию
- [ ] в реализации ссылка на задание
это готово. Вот так нужно?

- [ ]

2024-06-04 03:24 UTC, zinka22 commented on pytest_style.py
> +    result = subprocess.run(["python", "check_registration_form.py"])
в день просмотра время кончилось. сделаю

(с оборачиванием в функцию читала, мне так больше всего понравилось. На момент изменений на вызов из файла решила, что так сильно менять файл нельзя)

2024-06-04 03:29 UTC, zinka22 commented on requirements.txt
> +pytest~=8.2.1
сделано

2024-06-04 03:38 UTC, zinka22 commented on tasks/pytest_style.md
> +с помощью PyTest. В выводе найдите последнюю строку, скопируйте её и отправьте в это задание. Отправьте текст, который
сделала

2024-06-04 08:01 UTC, Cliffart44 requested changes

2024-06-04 08:01 UTC, Cliffart44 commented on requirements.txt
> +pytest~=8.2.1
> P
> Q
> R
> ⚠️ __S__
> ⚠️ __T__
> U
> V
> W
...

2024-06-04 08:01 UTC, Cliffart44 commented on pytest_style.py
> +# Задание содержится в tasks/pytest_style.md
Да, так же первые и сделаны 😺 
Ну и ещё в README запись добавляется в таблицу.

2024-06-04 10:58 UTC, zinka22 commented on requirements.txt
> +pytest~=8.2.1
сделала

2024-06-04 11:08 UTC, Cliffart44 commented on requirements.txt
> +pytest~=8.2.1
Жду коммит 😉

2024-06-04 11:10 UTC, zinka22 commented on pytest_style.py
> +    result = subprocess.run(["python", "check_registration_form.py"])
сделала, влила, тут все

2024-06-04 11:10 UTC, zinka22 commented on README.md
> +|         [Вывод pytest](tasks/pytest_style.md)         |     [pytest_style](pytest_style.py)     |
сделала

2024-06-04 11:11 UTC, zinka22 commented on requirements.txt
> +pytest~=8.2.1
готово)проверяла, что на все ответила

2024-06-04 11:26 UTC, zinka22 commented on pytest_style.py
> +def test_check_registration_form_link2():
сделала руками, просроченный не дает сделать коммит
![image](https://github.com/zinka22/Selenium-cource/assets/108293161/f17b7bb0-5156-41e5-b89f-f1227b58f7ac)

2024-06-04 11:29 UTC, Cliffart44 commented on pytest_style.py
> +def test_check_registration_form_link2():
Это да.

2024-06-04 11:30 UTC, zinka22 commented on pytest_style.py
> +def test_check_registration_form_link1():
сделала руками, просроченный не дает 
![image](https://github.com/zinka22/Selenium-cource/assets/108293161/28bbcf0a-2783-47a8-802c-e06bcc4e64e4)

2024-06-04 11:39 UTC, Cliffart44 requested changes
Финальные штрихи сам сделаю 🖌

2024-06-04 11:39 UTC, Cliffart44 commented on tasks/pytest_style.md
> +PS Обратите внимание - предупреждений (warnings) в вашем ответе быть не должно.
```suggestion
P.S. Обратите внимание — предупреждений (warnings) в вашем ответе быть не должно.
```

2024-06-04 11:39 UTC, Cliffart44 commented on tasks/pytest_style.md
> +[check_registration_with_bugz](../check_registration_with_bugz.py))
```suggestion
[check_registration_with_bugs](../check_registration_with_bugz.py))
```

2024-06-04 11:43 UTC, Cliffart44 approved these changes

2024-06-04 11:44 UTC, merged

2024-06-04 17:58 UTC, zinka22 commented on README.md
> +| [Вывод PyTest](tasks/pytest_style.md) | [pytest_style](pytest_style.py)|
руками в гитхабе решала конфликты