Смена time.sleep() на явные ожидания
zinka22/Selenium-cource pull request #23
Opened 2024-06-04 18:42 UTC by zinka22

* добавила вариант явного ожидания в файлах, которые были использованы в #18

источник задания https://github.com/zinka22/Selenium-cource/pull/18#discussion_r1615660337

2024-06-04 19:00 UTC, zinka22 commented
тут нужно менять time.sleep(10) в helper?

сейчас там вот так 
```def wait_ten_seconds_and_close(browser):
    if browser:
        time.sleep(10)
        browser.quit()
```

2024-06-05 04:48 UTC, Cliffart44 requested changes
А в целом да, это что нужно — теперь ожидания не общие, а конкретные.

2024-06-05 04:48 UTC, Cliffart44 commented on check_registration_form.py
> +from selenium.webdriver.support import expected_conditions as EC
https://github.com/zinka22/Selenium-cource/pull/13#discussion_r1615260093

2024-06-05 17:29 UTC, zinka22 commented on check_registration_form.py
> +from selenium.webdriver.support import expected_conditions as EC
готово, в 2х файлах понизила

2024-06-06 07:15 UTC, Cliffart44 approved these changes

2024-06-06 07:16 UTC, merged