Решение: изменение наименования элемента х
zinka22/Selenium-cource pull request #24
Opened 2024-06-05 10:22 UTC by zinka22

В одном из решений (switch_to_window) добавила новый вариант имени переменной для величины х, которую берем с экрана браузера, чтобы подставить в математическое выражение.

Когда придем к согласию по имени, сделаю то же имя во всех решениях, а именно:
solutions/confirm_alert.py
solutions/expected_conditions.py
solutions/switch_to_window.py
execute_script_scroll.py
get_attribute.py
radio_and_checkbox.py

2024-06-05 12:46 UTC, Cliffart44 requested changes

2024-06-05 12:46 UTC, Cliffart44 commented on solutions/switch_to_window.py
>      math_result = helpers.solve_math_expression_for_captcha(element_x_int)
Хорошо, можно оттолкнуться от страницы и `input_value` там. Но сейчас-то передаваемый аргумент так и остался `element_x_int`
Стало быть, в текущем контексте всё должно выглядеть примерно так:
```python
    input_value_element = browser.find_element(By.ID, "input_value")
    input_value_text = int(input_value_element.text)
    math_result = helpers.solve_math_expression_for_captcha(input_value_text)
```

---
Если же это привести к виду [expected_conditions.py](https://github.com/zinka22/Selenium-cource/pull/13#discussion_r1615260480), то получится вот что:
```python
    input_value = int(browser.find_element(By.ID, "input_value").text)
    math_result = helpers.solve_math_expression_for_captcha(input_value)
```

---
Так как цель в том, чтобы сделать код не только более точным, но и лаконичным, и раз тут [имеет место математическая функция](https://www.perplexity.ai/search/Inabs12sinx-0vW.JqCLQyGbzL3t85No1Q), а также есть цель [получить её частное значение](https://ru.wikipedia.org/wiki/%D0%A4%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D1%8F_(%D0%BC%D0%B0%D1%82%D0%B5%D0%BC%D0%B0%D1%82%D0%B8%D0%BA%D0%B0)#:~:text=%D0%B8%D0%BB%D0%B8%20%D0%B0%D1%80%D0%B3%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D0%BE%D0%BC%20%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B8%3B-,%D1%8D%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82,.,-%D0%BC%D0%BD%D0%BE%D0%B6%D0%B5%D1%81%D1%82%D0%B2%D0%BE%20%D0%B2%D1%81%D0%B5%D1%85%20%D1%87%D0%B0%D1%81%D1%82%D0%BD%D1%8B%D1%85)) при определённом вводе, то можно уточнить и имя вспомогательной функции в helpers. Тогда получится вот что:
```python
    input_value = int(browser.find_element(By.ID, "input_value").text)
    math_result = helpers.get_math_function_value(input_value)
```

---
![image](https://github.com/zinka22/Selenium-cource/assets/64852774/c903a008-36c7-41fd-9705-6b1ffde9ce40)
Кстати, если нажать здесь `R` после переименования, то PyCharm сам обновит все обращения к этой функции.

Куда делось "..._for_captcha"? Эта информация уже есть в docstring:
![image](https://github.com/zinka22/Selenium-cource/assets/64852774/8dc094ab-4572-45f2-b6d4-5bb0ba6ac298)

---
Также для сохранения консистентности можно обновить имя второй переменной:
```python
    function_value = helpers.get_math_function_value(input_value)
```

2024-06-05 18:22 UTC, zinka22 commented on solutions/switch_to_window.py
>      math_result = helpers.solve_math_expression_for_captcha(element_x_int)
везде согласна

1) чтобы удобнее было делать #20, сделала так, как в комментарии

> Если же это привести к виду [expected_conditions.py](https://github.com/zinka22/Selenium-cource/pull/13#discussion_r1615260480), то получится вот что:
> 
> ```python
>     input_value = int(browser.find_element(By.ID, "input_value").text)
>     math_result = helpers.solve_math_expression_for_captcha(input_value)
> ```

2) изменила имя функции в helpers, чтобы было единообразно с переменной и поиском значения выражения

2024-06-06 07:10 UTC, Cliffart44 approved these changes

2024-06-06 07:11 UTC, merged