Перенос файла с заданием: fill the huge form
zinka22/Selenium-cource pull request #28
Opened 2024-06-06 19:24 UTC by zinka22

1) сделала md файл с заданием fill the huge form.md
2) в README для задачи убрала абсолютную ссылку, добавила относительную ссылку на md file и ссылку на py
3) добавила комментарий в fill the huge form.py с местом нахождения задания

2024-06-06 19:39 UTC, Cliffart44 requested changes
Также в solutions/fill_the_huge_form.py сразу стоит уточнить имена переменных.

2024-06-06 19:39 UTC, Cliffart44 commented on README.md
>  |    [Поиск элемента по XPath](tasks/fill_the_form_with_XPath.md)    |   [fill_the_form_with_XPath](solutions/fill_the_form_with_XPath.py)   |
```suggestion
|    [Поиск элемента по XPath](tasks/fill_the_form_with_XPath.md)    |   [fill_the_form_with_XPath](solutions/fill_the_form_with_XPath.py)   |
|     [Использование find_elements](tasks/fill_the_huge_form.md)     |         [fill_the_huge_form](solutions/fill_the_huge_form.py)         |
```

2024-06-06 19:39 UTC, Cliffart44 commented on tasks/fill_the_huge_form.md
> +форму 100 обязательных полей и ограничив время на ее заполнение.
```suggestion
форму 100 обязательных полей и ограничив время на её заполнение.
```

2024-06-06 19:39 UTC, Cliffart44 commented on tasks/fill_the_huge_form.md
> +Используйте WebDriver, метод find_elements, нужные локатор и его значение. Здесь можно прописать цикл for, который
```suggestion
Используйте `WebDriver`, метод `find_elements`, нужный локатор и его значение. Здесь можно прописать цикл `for`, который
```

2024-06-07 03:59 UTC, zinka22 commented
> Также в solutions/fill_the_huge_form.py сразу стоит уточнить имена переменных.

сделала

2024-06-07 09:25 UTC, Cliffart44 approved these changes

2024-06-07 09:26 UTC, merged