Перенос файла с заданием: check registration form
zinka22/Selenium-cource pull request #33
Opened 2024-06-09 20:30 UTC by zinka22

1) сделала md файл с заданием check registration form.md
2) в README для задачи убрала абсолютную ссылку, добавила относительную ссылку на md file и ссылку на py
3) добавила комментарий в check registration form.py с местом нахождения задания

2024-06-10 07:32 UTC, Cliffart44 requested changes

2024-06-10 07:32 UTC, Cliffart44 commented on tasks/check_registration_form.md
> +4) проверить, что текст с сообщением об успехе совпадает с ожидаемым текстом
![image](https://github.com/zinka22/Selenium-cource/assets/64852774/5505a276-072c-41f6-8b27-3ebc72f125f2)

2024-06-10 07:32 UTC, Cliffart44 commented on tasks/fill_the_form_with_XPath.md
>  Но сработает только кнопка с текстом "Submit", и наша задача нажать в коде именно на неё.
```suggestion
отправки. Но сработает только кнопка с текстом "Submit", и наша задача нажать в коде именно на неё.
```

2024-06-10 07:32 UTC, Cliffart44 commented on tasks/check_registration_form.md
> +   "Congratulations! You have successfully registered!"(использовать assert);
```suggestion
   "Congratulations! You have successfully registered!" (использовать assert);
```

2024-06-10 07:32 UTC, Cliffart44 commented on solutions/check_registration_form.py
> +
Здесь тоже актуально https://github.com/zinka22/Selenium-cource/pull/28#pullrequestreview-2103046259.

2024-06-10 18:18 UTC, zinka22 commented on tasks/check_registration_form.md
> +4) проверить, что текст с сообщением об успехе совпадает с ожидаемым текстом
никто не удивляется

2024-06-10 18:30 UTC, zinka22 commented on solutions/check_registration_form.py
> +
сделала

2024-06-10 18:37 UTC, Cliffart44 requested changes
Конфликты появились после #32.

2024-06-10 18:37 UTC, Cliffart44 commented on tasks/check_registration_form.md
> +   "Congratulations! You have successfully registered!" (использовать assert);
```suggestion
   "Congratulations! You have successfully registered!" (использовать `assert`);
```

2024-06-10 18:42 UTC, Cliffart44 commented on solutions/check_registration_form.py
>      )
#30

2024-06-10 19:41 UTC, zinka22 commented
> Конфликты появились после #32.

сделала rebase, в середине отвлеклась и пропустила в одном месте конфликты. Возвращалась, делала rebase второй раз.

Конфликты в md файле "вплелись" друг в друга, правила руками. Могла потерять ранее предложенные изменения.

2024-06-11 02:32 UTC, Cliffart44 commented
> > Конфликты появились после #32.
> 
> сделала rebase, в середине отвлеклась и пропустила в одном месте конфликты. Возвращалась, делала rebase второй раз.
> 
> Конфликты в md файле "вплелись" друг в друга, правила руками. Могла потерять ранее предложенные изменения в md файлах (tasks/fill_the_form_with_XPath.md и tasks/check_registration_form.md)

В этом смысле `git merge` проще — при такой операции нужно было бы решить конфликт только в tasks/fill_the_form_with_XPath.md.

2024-06-11 02:41 UTC, Cliffart44 approved these changes

2024-06-11 02:42 UTC, merged