Перенос файла с заданием: upload file from pc
zinka22/Selenium-cource pull request #38
Opened 2024-06-11 20:06 UTC by zinka22

1) сделала md файл с заданием upload file from pc.md
2) в README для задачи убрала абсолютную ссылку, добавила относительную ссылку на md file и ссылку на py
3) добавила комментарий в upload file from pc.py с местом нахождения задания

2024-06-12 08:11 UTC, Cliffart44 requested changes
В целом всё хорошо, но нужно доделать md-файлы и решить конфликты.

2024-06-12 08:11 UTC, Cliffart44 commented on tasks/upload_file_from_pc.md
> +   Отправьте полученное число в качестве ответа для этого задания.
```suggestion
5) если всё сделано правильно и быстро, вы увидите окно с числом.
```

2024-06-12 08:11 UTC, Cliffart44 commented on README.md
```suggestion
```

2024-06-12 08:11 UTC, Cliffart44 commented on tasks/upload_file_from_pc.md
> +3) загрузить файл. Файл должен иметь расширение .txt и может быть пустым;
Расширение — это по определению то, что идёт после точки 🙂

```suggestion
3) загрузить файл. Файл должен иметь расширение txt и может быть пустым;
```

2024-06-12 18:10 UTC, zinka22 commented on tasks/upload_file_from_pc.md
> +   Отправьте полученное число в качестве ответа для этого задания.
> Тут же ничего никуда отправлять не нужно?

в рамках реализации не нужно ничего отправлять

2024-06-12 18:16 UTC, zinka22 commented
> В целом всё хорошо, но нужно доделать md-файлы и решить конфликты.

сделала

2024-06-12 19:29 UTC, Cliffart44 commented
> > В целом всё хорошо, но нужно доделать md-файлы и решить конфликты.
> 
> сделала

Ну что, последний файл уже и Issue закрывается окончательно 🙂
На твой взгляд, как выглядит теперь код? Стало удобнее, проще и красивее? Тебе самой нравится результат работы; то, как ты оформила теперь учебный курс?

2024-06-13 06:28 UTC, Cliffart44 approved these changes
Жду ответ по https://github.com/zinka22/Selenium-cource/pull/38#issuecomment-2163755144 и сливаю 🙂

2024-06-13 06:28 UTC, Cliffart44 commented on README.md
> +|                 [Сheckboxes и radiobuttons](tasks/radio_and_checkbox.md)                 |            [radio_and_checkbox](solutions/radio_and_checkbox.py)            |
```suggestion
|                 [Checkboxes и radiobuttons](tasks/radio_and_checkbox.md)                 |            [radio_and_checkbox](solutions/radio_and_checkbox.py)            |
```

2024-06-13 06:38 UTC, zinka22 commented
Выглядит отлично.

Дальше прибавится еще много задач (когда сделаю) и придут проверять сокурсники (неизвестные).

Кстати они ничего не могут же натыкать, репозиторий защищен, верно?

2024-06-13 06:39 UTC, zinka22 commented
> Жду ответ по [#38 (comment)](https://github.com/zinka22/Selenium-cource/pull/38#issuecomment-2163755144) и сливаю 🙂

Опять русская с наверное)

2024-06-13 06:40 UTC, Cliffart44 commented
> Выглядит отлично.
> 
> Дальше прибавится еще много задач (когда сделаю) и придут проверять сокурсники (неизвестные).
> 
> Кстати они ничего не могут же натыкать, репозиторий защищен, верно?

Хорошо! Они могут создать pull request при желании 🙂

2024-06-13 06:41 UTC, merged