Задача: авторизация на сайте с использованием pytest (test_authorization)
zinka22/Selenium-cource pull request #39
Opened 2024-06-13 20:08 UTC by zinka22

Тут добавила:
1) задание authorization.md в папку tasks
2) папку pytest_folder: реализация, json файл (в удаленном репозитории его нет), conftest.py
3) реализацию test_authorization.py в папку pytest_folder
4) строку в README.md с ссылкой на md и py файлы

2024-06-14 10:26 UTC, Cliffart44 requested changes
Возможно, по итогам этой задачи добавится одна Issue (маленькая) 😉

2024-06-14 10:26 UTC, Cliffart44 commented on .gitignore
> +auth_keys_stepik.json
```suggestion
.idea/

```

В связке с https://github.com/zinka22/Selenium-cource/pull/39#discussion_r1639491447.

2024-06-14 10:26 UTC, Cliffart44 commented on solutions/pytest_folder/conftest.py
> +import json
Сортировка импортов плюс https://github.com/zinka22/Selenium-cource/pull/39#discussion_r1639467712.

```suggestion
import json
from pathlib import Path

import pytest
from selenium import webdriver
```

2024-06-14 10:26 UTC, Cliffart44 commented on solutions/pytest_folder/conftest.py
> +def auth_data():
Стоит добавить сюда возвращаемый тип — как в
https://github.com/zinka22/Selenium-cource/blob/2c4fdf7c23ac3e6a460323d8e433f802f5536f8d/helpers.py#L9

Также стоит добавить docstring.

2024-06-14 10:26 UTC, Cliffart44 commented on solutions/pytest_folder/conftest.py
> +        return auth_data
Рекомендовал бы использовать [pathlib](https://realpython.com/python-pathlib/) (и [не только я](https://treyhunner.com/2019/01/no-really-pathlib-is-great/)):
```python
    auth_path = Path("auth_keys_stepik.json")
    return json.loads(auth_path.read_text())
```

При этом для универсальной работы и из терминала, и из интерфейса PyCharm можно использовать несколько видоизменённый код:
```suggestion
    auth_path = Path().rglob("auth_keys_stepik.json")
    return json.loads(next(auth_path).read_text())
```

2024-06-14 10:26 UTC, Cliffart44 commented on tasks/authorization.md
> +и не добавляйте свои логин и пароль в публичные репозитории на GitHub.
При этом пустой файл auth_keys_stepik.json создать всё таки имеет смысл. Или даже не пустой, а с чем-то типа 
```json
{
  "login": "example@example.ex",
  "password": "example"
}
```

В связке с https://github.com/zinka22/Selenium-cource/pull/39#discussion_r1639402362.

2024-06-14 10:26 UTC, Cliffart44 commented on README.md
> +|                      [Авторизация на сайте](tasks/authorization.md)                      |     [test_authorization](solutions/pytest_folder/test_authorization.py)     |
До настоящего момента имена md-файлов соответствовали именам py-файлов. Действительно есть основания менять подход?

2024-06-14 10:26 UTC, Cliffart44 commented on tasks/authorization.md
> +Вам необходимо авторизоваться на stepik со своим логином и паролем. Пожалуйста, будьте внимательны
Здесь нигде ни про pytest, ни про порядок запуска теста ни слова. Думаю, такая информация не помешает 🙂

По мотивам https://github.com/zinka22/Selenium-cource/pull/39#discussion_r1639467712 😉

2024-06-14 10:26 UTC, Cliffart44 commented on tasks/authorization.md
> +Задача - реализовать автотест со следующим набором действий:
```suggestion
Задача — реализовать автотест со следующим набором действий:
```

2024-06-14 17:08 UTC, zinka22 commented on README.md
> +|                      [Авторизация на сайте](tasks/authorization.md)                      |     [test_authorization](solutions/pytest_folder/test_authorization.py)     |
сделала
тут скорее ошибка: название было authorization, без слова тест pytest не видел тест)

2024-06-14 17:10 UTC, Cliffart44 commented on tasks/authorization.md
> +и не добавляйте свои логин и пароль в публичные репозитории на GitHub.
@zinka22, это можно сделать в процессе перебазирования, кстати.

2024-06-14 17:32 UTC, zinka22 commented on solutions/pytest_folder/conftest.py
> +        return auth_data
> Рекомендовал бы использовать [pathlib](https://realpython.com/python-pathlib/) (и [не только я](https://treyhunner.com/2019/01/no-really-pathlib-is-great/)):
> 
> ```python
>     auth_path = Path("auth_keys_stepik.json")
>     return json.loads(auth_path.read_text())
> ```
> 
> При этом для универсальной работы и из терминала, и из интерфейса PyCharm можно использовать несколько видоизменённый код:

прочитала, пока сложно. Оставила в notion, буду использовать

2024-06-14 17:39 UTC, Cliffart44 commented
Да, поэтому и написал готовый код. Между прочим, и самому пришлось посидеть
и поразбираться с этим.

пт, 14 июн. 2024 г. в 21:33, Natali ***@***.***>:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In solutions/pytest_folder/conftest.py
> <https://github.com/zinka22/Selenium-cource/pull/39#discussion_r1640151210>
> :
>
> > +    with open("auth_keys_stepik.json", "r") as data:
> +        auth_data = json.load(data)
> +        return auth_data
>
> Рекомендовал бы использовать pathlib
> <https://realpython.com/python-pathlib/> (и не только я
> <https://treyhunner.com/2019/01/no-really-pathlib-is-great/>):
>
>     auth_path = Path("auth_keys_stepik.json")
>     return json.loads(auth_path.read_text())
>
> При этом для универсальной работы и из терминала, и из интерфейса PyCharm
> можно использовать несколько видоизменённый код:
>
> прочитала, пока сложно. Оставила в notion, буду использовать
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/zinka22/Selenium-cource/pull/39#discussion_r1640151210>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APOZGJVMP5WXPDHDCPKKW4LZHMSM5AVCNFSM6AAAAABJJCKXPOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDCMJYHEZDQMRVGM>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2024-06-14 17:40 UTC, Cliffart44 commented on solutions/pytest_folder/conftest.py
> +        return auth_data
Да, поэтому и написал готовый код. Между прочим, и самому пришлось посидеть
и поразбираться с этим.

2024-06-14 17:52 UTC, zinka22 commented on solutions/pytest_folder/conftest.py
> +def auth_data():
сделала

2024-06-14 17:53 UTC, zinka22 commented on tasks/authorization.md
> +и не добавляйте свои логин и пароль в публичные репозитории на GitHub.
вот это как раз не сделала, вовремя написал

2024-06-14 18:08 UTC, zinka22 commented on tasks/authorization.md
> +Вам необходимо авторизоваться на stepik со своим логином и паролем. Пожалуйста, будьте внимательны
плохо поняла задачу
* про то, что нужно запускать через pytest написала
* про порядок запуска наверное не написала. Добавила, что нужно изменить данные в auth_keys_stepik.json на свои и что запуск pytest без дополнительных настроек. Если не так, нужно пояснение

2024-06-14 18:19 UTC, Cliffart44 requested changes

2024-06-14 18:19 UTC, Cliffart44 commented on README.md
> +|                   [Авторизация на сайте](tasks/test_authorization.md)                    |     [test_authorization](solutions/pytest_folder/test_authorization.py)     |
https://github.com/zinka22/Selenium-cource/pull/13#discussion_r1615259880

2024-06-14 18:19 UTC, Cliffart44 commented on solutions/pytest_folder/test_authorization.py
> +from selenium.webdriver.common.by import By
Иоги, пункт 2: https://github.com/zinka22/Selenium-cource/pull/11#issuecomment-2120114060.

2024-06-14 18:19 UTC, Cliffart44 commented on tasks/authorization.md
> +Вам необходимо авторизоваться на stepik со своим логином и паролем. Пожалуйста, будьте внимательны
1. Где? 
![image](https://github.com/zinka22/Selenium-cource/assets/64852774/eaadc772-f81e-4237-aca7-12402b0f2650)
2. Этого тоже не вижу пока.

2024-06-14 19:16 UTC, zinka22 commented on tasks/authorization.md
> +Вам необходимо авторизоваться на stepik со своим логином и паролем. Пожалуйста, будьте внимательны
сделала комит локально и верила, что на rebase 5 минут

отписалась и не сделала пуш, виновата

2024-06-14 19:16 UTC, zinka22 commented on README.md
> +|                   [Авторизация на сайте](tasks/test_authorization.md)                    |     [test_authorization](solutions/pytest_folder/test_authorization.py)     |
сделала

2024-06-14 19:19 UTC, zinka22 commented on solutions/pytest_folder/test_authorization.py
> +from selenium.webdriver.common.by import By
сделала

2024-06-15 04:01 UTC, Cliffart44 requested changes
И потом всё таки не помешает научиться делать перебазирование за 5⃣ минут с сохранением изначальной структуры коммитов (говорили примерно об этом здесь: https://github.com/zinka22/Selenium-cource/pull/11#pullrequestreview-2060574409).

Напиши, пожалуйста, как делала в этот раз.

2024-06-15 04:01 UTC, Cliffart44 commented on solutions/pytest_folder/auth_keys_stepik.json
> +}
[Причины](https://stackoverflow.com/a/729795).

```suggestion
}

```

2024-06-15 04:01 UTC, Cliffart44 commented on README.md
> +|                      [Авторизация на сайте](tasks/authorization.md)                      |     [test_authorization](solutions/pytest_folder/test_authorization.py)     |
Дефект. 

Также зачем нужны https://github.com/zinka22/Selenium-cource/commit/5976c9fb0b7d3d1cd3ec3808e08a487247d0a7e3 и d78677013494620f38a5343088567119d443e311?

2024-06-15 04:01 UTC, Cliffart44 commented on solutions/pytest_folder/conftest.py
> +    and return them as a dictionary
```suggestion
    and return them as a dictionary.
```

2024-06-15 04:01 UTC, Cliffart44 commented on tasks/test_authorization.md
> +1) забрать к себе папку pytest_folder;
У кого? 😄

Можно либо опустить этот пункт вообще (нельзя запустить то, чего нет), либо перефразировать.

К тому же, кто-то может только скопировать код, а файлы создать свои 🤷🏻‍♂️

2024-06-15 04:01 UTC, Cliffart44 commented on tasks/test_authorization.md
> +3) запустить тест в терминале при помощи команды pytest <путь к файлу>.
Ну и тогда стоит упомянуть запуск из PyCharm — он же тоже поддерживается.

2024-06-15 16:10 UTC, Cliffart44 commented on README.md
> +|                   [Авторизация на сайте](tasks/test_authorization.md)                    |     [test_authorization](solutions/pytest_folder/test_authorization.py)     |
Ещё раз, пожалуйста.

2024-06-15 16:15 UTC, Cliffart44 commented on tasks/authorization.md
> +и не добавляйте свои логин и пароль в публичные репозитории на GitHub.
Восстановил структуру коммитов и это теперь снова актуально. Напиши, пожалуйста, https://github.com/zinka22/Selenium-cource/pull/39#pullrequestreview-2119920519 здесь 🙂

2024-06-17 03:36 UTC, zinka22 commented
> И потом всё таки не помешает научиться делать перебазирование за 5 минут с сохранением изначальной структуры коммитов (говорили примерно об этом здесь: [#11 (review)](https://github.com/zinka22/Selenium-cource/pull/11#pullrequestreview-2060574409)).
> 
> Напиши, пожалуйста, как делала в этот раз.

1) долго не могла попасть в первый коммит в ветке, попадала во второй пока не сделала как ты писал в https://github.com/zinka22/Selenium-cource/pull/11#pullrequestreview-2060574409
2) интерактивный забыла, искала, как писать в редакторе интерактивного rebase
3) сделала rebase, переписав только 1й коммит
4) сделала пуш в удаленный - проверила, что у меня там +несколько файлов изменено привязалось с main ветки (как-не поняла)
5) пошла обратно, возвращалась в место до rebase
6) уже все, устала расстроилась, когда делала второй раз сделала rebase и оставила коммиты первый последний и твои изменения, остальным написала squash (там коммиты были "убрала лишнюю точку, добавила пробел после строки", показались неважными

2024-06-17 07:58 UTC, Cliffart44 commented
@zinka22, https://github.com/zinka22/Selenium-cource/pull/39#discussion_r1641275957. Иначе по всему PR потом сообщения собирать 😆

2024-06-17 10:21 UTC, zinka22 commented on tasks/authorization.md
> +и не добавляйте свои логин и пароль в публичные репозитории на GitHub.
1) долго не могла попасть в первый коммит в ветке, попадала во второй пока не сделала как ты писал в https://github.com/zinka22/Selenium-cource/pull/11#pullrequestreview-2060574409
2) интерактивный забыла, искала, как писать в редакторе интерактивного rebase
3) сделала rebase, переписав только 1й коммит
4) сделала пуш в удаленный - проверила, что у меня там +несколько файлов изменено привязалось с main ветки (как-не поняла)
5) пошла обратно, возвращалась в место до rebase
6) уже все, устала расстроилась, когда делала второй раз сделала rebase и оставила коммиты первый последний и твои изменения, остальным написала squash (там коммиты были "убрала лишнюю точку, добавила пробел после строки", показались неважными

2024-06-17 10:27 UTC, Cliffart44 commented on tasks/authorization.md
> +и не добавляйте свои логин и пароль в публичные репозитории на GitHub.
В целом можно делать и так, конечно, но пока что не стоит смешивать несколько задач в одну операцию, чтобы не путаться.
Сейчас вспомнила как делается интерактивное перебазирование?

2024-06-17 10:34 UTC, zinka22 commented on tasks/authorization.md
> +и не добавляйте свои логин и пароль в публичные репозитории на GitHub.
вспомнила, записала
ты вот тут https://github.com/zinka22/Selenium-cource/pull/11#pullrequestreview-2060574409 нормально написал как делать

основная загвоздка была попасть ровно в первый

2024-06-18 10:59 UTC, zinka22 commented on tasks/test_authorization.md
> +3) запустить тест в терминале при помощи команды pytest <путь к файлу>.
сделала

2024-06-18 11:01 UTC, zinka22 commented on tasks/test_authorization.md
> +1) забрать к себе папку pytest_folder;
убрала строку

2024-06-18 13:34 UTC, Cliffart44 requested changes
Тест не падает при неудачной авторизации — стоит добавить какую-либо проверку этого ([источник](https://github.com/zinka22/Selenium-cource/pull/39/files#diff-7c01c17f3f5e851be27bfdbae15f62845599cceb77449d9c47243ed16883bbdeR12)).

2024-06-18 18:18 UTC, zinka22 commented
сделала

2024-06-18 18:20 UTC, zinka22 commented
> Тест не падает при неудачной авторизации — стоит добавить какую-либо проверку этого ([источник](https://github.com/zinka22/Selenium-cource/pull/39/files#diff-7c01c17f3f5e851be27bfdbae15f62845599cceb77449d9c47243ed16883bbdeR12)).

* сделала проверку, что попап с введенным логином и паролем закрылся

* увеличила таймаут в conftest.py

2024-06-18 19:56 UTC, Cliffart44 approved these changes

2024-06-18 19:56 UTC, Cliffart44 commented on solutions/pytest_folder/test_authorization.py
> +# Задание содержится в tasks/test_authorization.md
```suggestion
# Задание содержится в tasks/test_authorization.md

```

2024-06-18 19:56 UTC, Cliffart44 commented on solutions/pytest_folder/test_authorization.py
> +            popup_was_closed = WebDriverWait(browser, 5).until(
```suggestion
            popup_is_closed = WebDriverWait(browser, 5).until(
```

2024-06-18 19:56 UTC, Cliffart44 commented on solutions/pytest_folder/test_authorization.py
> +            return popup_was_closed
```suggestion
            return popup_is_closed
```

2024-06-18 20:00 UTC, merged