Задача: параметризация тестов (task_parametrization)
zinka22/Selenium-cource pull request #41
Opened 2024-06-21 19:10 UTC by zinka22

Тут добавила:

1) задание  test_parametrization.md в папку tasks
2) реализацию test_parametrization.py в папку pytest_folder
3) строку в README.md с ссылкой на md и py файлы

2024-06-23 17:01 UTC, Cliffart44 requested changes
Тесты успешны даже при неудачной авторизации — такого явно быть не должно.

2024-06-23 17:01 UTC, Cliffart44 commented on solutions/pytest_folder/test_parametrization.py
> +    # авторизация
Тут же место для docstring 😉

2024-06-23 17:01 UTC, Cliffart44 commented on solutions/pytest_folder/test_parametrization.py
> +            pass
Почему при таком исключении продолжается выполнение?

2024-06-23 17:01 UTC, Cliffart44 commented on solutions/pytest_folder/test_parametrization.py
> +        assert feedback_text == "Correct!", f"Wait {'Correct!'} got {feedback_text}"
```python
...{'Correct!'}...
```
Зачем тут скобки?

И сообщение об ошибке стоит согласовать по времени (и запятую поставить): либо "Ждать-получать", либо "Ждал-получил". Сейчас, соответственно, "Ждать-получил".

2024-06-23 17:01 UTC, Cliffart44 commented on solutions/pytest_folder/test_parametrization.py
> +        return
Это что даёт?

2024-06-23 17:01 UTC, Cliffart44 commented on tasks/test_parametrization.md
> +```import time
```suggestion
```python
import time
```

2024-06-23 17:01 UTC, Cliffart44 commented on tasks/test_parametrization.md
> +https://stepik.org/lesson/236905/step/1
```suggestion
- https://stepik.org/lesson/236895/step/1
- https://stepik.org/lesson/236896/step/1
- https://stepik.org/lesson/236897/step/1
- https://stepik.org/lesson/236898/step/1
- https://stepik.org/lesson/236899/step/1
- https://stepik.org/lesson/236903/step/1
- https://stepik.org/lesson/236904/step/1
- https://stepik.org/lesson/236905/step/1
```

2024-06-23 17:01 UTC, Cliffart44 commented on tasks/test_parametrization.md
> +_______________________________
```suggestion

_______________________________
```

2024-06-23 17:01 UTC, Cliffart44 commented on tasks/test_parametrization.md
> +строкой "Correct!" Соберите кусочки текста в одно предложение и отправьте в качестве ответа на это задание.
```suggestion
строкой "Correct!". Соберите кусочки текста в одно предложение и отправьте в качестве ответа на это задание.
```

2024-06-23 17:01 UTC, Cliffart44 commented on tasks/test_parametrization.md
> +время (https://time.is/ru/). Ответ для каждой задачи нужно пересчитывать отдельно, иначе они устаревают.
```suggestion
время (https://time.is/ru/). Ответы для каждой задачи нужно пересчитывать отдельно, иначе они устаревают. 
```

Иначе получается, что устаревают задачи.

2024-06-23 17:01 UTC, Cliffart44 commented on solutions/pytest_folder/test_parametrization.py
> +        """Check if user was authorized"""
```suggestion
        """Check if the user is authorized."""
```

2024-06-23 17:01 UTC, Cliffart44 commented on solutions/pytest_folder/test_parametrization.py
> +    def user_is_authorised():
Не стоит дублировать код.

2024-06-24 11:10 UTC, zinka22 commented on solutions/pytest_folder/test_parametrization.py
> +            pass
план был, что на протяжении 15 секунд идем кнопку "Решить снова"
если ее нет и 15 секунд уже прошли, при появлении TimeException ее больше не искать - считаем что поле пустое.

вписала pass получилось) Видимо двойная ошибка произошла и тут работать не должно? 
Почему - не вижу.

2024-06-24 11:14 UTC, zinka22 commented on solutions/pytest_folder/test_parametrization.py
> +        return
пара минут сделаю пуш, тут убрала return и сделала assert на проверку авторизован ли пользователь

2024-06-24 11:20 UTC, zinka22 commented on solutions/pytest_folder/test_parametrization.py
> +    # авторизация
добавила docstring

2024-06-24 11:21 UTC, zinka22 commented on solutions/pytest_folder/test_parametrization.py
> +        assert feedback_text == "Correct!", f"Wait {'Correct!'} got {feedback_text}"
убрала скобки, изменила время с got на get

2024-06-24 11:23 UTC, zinka22 commented on solutions/pytest_folder/test_parametrization.py
> +    def user_is_authorised():
есть 2 файлика, куда можно унести эту функцию
1) helpers
2) conftest

хочу унести в конфтест, т.к. pytest с в нее смотрит даже без объявления (работает или нет еще не проверила)
т.е. тут нужно немного подумать, ответа пока нет

2024-06-24 15:04 UTC, Cliffart44 requested changes
Процесс идёт 🙂

2024-06-24 15:04 UTC, Cliffart44 commented on solutions/pytest_folder/test_authorization.py
> +    user_is_authorized = user_authorization_checker_factory()
Этот файл не относится к текущей задаче, поэтому вынеси, пожалуйста, эти изменения в отдельный pull request.

2024-06-24 15:04 UTC, Cliffart44 commented on solutions/pytest_folder/conftest.py
> +def user_authorization_checker_factory(browser):
Согласно [документации](https://docs.pytest.org/en/6.2.x/fixture.html#factories-as-fixtures)...
> The “factory as fixture” pattern can help in situations where the result of a fixture is needed multiple times in a single test.

Тут точно нужен такой подход?

2024-06-24 15:04 UTC, Cliffart44 commented on solutions/pytest_folder/test_parametrization.py
> +    # авторизация
В конце предложений ставятся ж точки?
Согласно [документации](https://peps.python.org/pep-0257/#one-line-docstrings)...
> The docstring is a phrase ending in a period.

[Ещё примеры](https://pym.dev/docstrings/?watch).

2024-06-24 15:04 UTC, Cliffart44 commented on solutions/pytest_folder/test_parametrization.py
> +            pass
Не пойму, почему этой кнопки может не быть — все страницы посмотрел сейчас, и на каждой кнопка есть. В таком случае зачем нужна...
> проверка, есть ли кнопка "Решить снова"

?

2024-06-24 15:04 UTC, Cliffart44 commented on tasks/test_parametrization.md
> +1) открыть страницу;
Какую?

2024-06-24 15:04 UTC, Cliffart44 commented on solutions/pytest_folder/test_parametrization.py
> +        assert feedback_text == "Correct!", f"Wait 'Correct!', get {feedback_text}"
Что скажешь насчёт такого?
```suggestion
        assert feedback_text == "Correct!", f"Expected 'Correct!' feedback text, actual is {feedback_text}."
```

2024-06-24 18:15 UTC, zinka22 commented on solutions/pytest_folder/test_parametrization.py
> +            pass
при первом прогоне листы "чистые"
при втором и последующем прогоне листы ранее заполнены (по крайней мере вот так поняла)

Написала, прогнала - тесты зеленые и три красные. Чуть переписала, прогнала - все красные, нет элемента) Начала искать - в задании написано, что при вводе в поле поле должно быть пустым. А если ранее я уже решала - полу заполнено.

2024-06-24 18:18 UTC, zinka22 commented on solutions/pytest_folder/conftest.py
> +def user_authorization_checker_factory(browser):
единственное что нашла. Нужна подсказка, где поискать.

2024-06-24 18:31 UTC, zinka22 commented on solutions/pytest_folder/test_parametrization.py
> +    # авторизация
прочла, добавила

2024-06-24 18:33 UTC, zinka22 commented on solutions/pytest_folder/test_authorization.py
> +    user_is_authorized = user_authorization_checker_factory()
файл убрала, отдельно не вынесла. Жду окончания переговоров по тому, куда и как user_is_athorized, чтобы не переделывать

2024-06-24 18:34 UTC, zinka22 commented on tasks/test_parametrization.md
> +1) открыть страницу;
добавила куда смотреть

2024-06-25 17:12 UTC, Cliffart44 requested changes

2024-06-25 17:12 UTC, Cliffart44 commented on tasks/test_parametrization.md
> +1) открыть страницу (список страниц для проверки указан ниже, смотри перечисление urls;
```suggestion
1) открыть страницу (список страниц для проверки указан ниже, смотри перечисление urls);
```

2024-06-25 17:12 UTC, Cliffart44 commented on solutions/pytest_folder/test_parametrization.py
> +            pass
Понял, что не особо удобен UI сайта. Но просто так ждать кнопку, которой может и не быть, да ещё и 15 секунд... Кажется, что многовато. Нельзя ли перейти на if-else в данном случае?

Плюс можно очищать поле в любом случае, даже если оно и так пустое (это практически мгновенно).

2024-06-25 17:12 UTC, Cliffart44 commented on solutions/pytest_folder/conftest.py
> +def user_authorization_checker_factory(browser):
А что мешает сделать как тут?
https://github.com/zinka22/Selenium-cource/blob/6c3350851d773d0e456a48f23086bab645320e81/helpers.py#L25

Дополнительно можно [посмотреть вот](https://lorepirri.com/pytest-register-assert-rewrite.html).

2024-06-26 19:10 UTC, zinka22 commented on solutions/pytest_folder/conftest.py
> +def user_authorization_checker_factory(browser):
убрала функцию из conftest, добавила функцию в helpers

2024-06-26 19:13 UTC, zinka22 commented on solutions/pytest_folder/test_parametrization.py
> +            pass
не сделала, завтра.

Зато в последнем коммите снова послала логин и пароль )
Вроде убрала. Посмотри, пожалуйста, тоже

2024-06-27 07:13 UTC, Cliffart44 requested changes
Уже почти всё готово 🙂

2024-06-27 07:13 UTC, Cliffart44 commented on solutions/pytest_folder/test_parametrization.py
> +            pass
С данными для авторизации всё нормально.

Со всем остальным — если можно сделать проще, то сделай. Если нет, то пусть остаётся имеющийся вариант (но хотя бы время ожидания минимальным сделай).

---
Но
> А сейчас мы будем пытаться найти кнопку 15 секунд. Ой, её нет? А, ну ладно, тогда просто пойдём дальше, не очень-то и хотелось её видеть... 🤷‍♀️

не выглядит хорошо 😆 Другое дело,
> Если есть кнопка, то нажми. Иначе просто продолжай выполнение.

2024-06-27 07:13 UTC, Cliffart44 commented on helpers.py
> +    """Check if user is authorized"""
Само по себе это очевидно из названия функции. Тут можно описать каким образом выполняется проверка.

2024-06-27 07:13 UTC, Cliffart44 commented on helpers.py
> +            return popup_is_closed
Объясни, пожалуйста, почему так лучше
```suggestion
            return True
```

2024-06-27 07:13 UTC, Cliffart44 commented on helpers.py
> +def check_if_user_is_authorized(browser):
Насколько понимаю, тут функции располагаются в алфавитном порядке?

2024-06-27 07:13 UTC, Cliffart44 commented on tasks/test_parametrization.md
> +____________________________________
Кстати, для корректного отображения достаточно трёх дефисов
```suggestion
---
```

2024-06-27 07:13 UTC, Cliffart44 commented on solutions/pytest_folder/test_parametrization.py
> +    # проверка, авторизован ли пользователь
Точно без этого комменттария не будет понятно, что за строка следом?

2024-06-27 07:13 UTC, Cliffart44 commented on solutions/pytest_folder/test_parametrization.py
> +    user_is_authorized = check_if_user_is_authorized(browser)
```suggestion
    is_user_authorized = check_if_user_is_authorized(browser)
```

Или, согласно [этой статье](https://michaelzanggl.com/articles/tips-on-naming-boolean-variables/)...
```python
    is_user_logged_in = check_if_user_is_authorized(browser)
```
На мой взгляд, так проще читается.

2024-06-27 07:13 UTC, Cliffart44 commented on solutions/pytest_folder/test_parametrization.py
> +        assert (
Тут и так скобка на отдельной строке, так что...
```suggestion
        )
        assert (
```

2024-06-27 17:03 UTC, zinka22 commented on solutions/pytest_folder/test_parametrization.py
> +            pass
Сделала явное ожидание на 5 секунд, проверила 2 раза: чему нужно падать падает, чему нужно проходить проходит.

Очистка поля по тапу на "Решить снова", искать что-то другое нет смысла.

2024-06-27 18:24 UTC, zinka22 commented on helpers.py
> +    """Check if user is authorized"""
сделала

2024-06-27 18:27 UTC, zinka22 commented on helpers.py
> +            return popup_is_closed
Лучше оставить true для читаемости. Иначе нужно перечитать что из себя представляет popup_is_closed, чтобы понять что возвращает функция.

2024-06-27 18:33 UTC, zinka22 commented on helpers.py
> +def check_if_user_is_authorized(browser):
отсортировала по алфавиту

2024-06-27 18:34 UTC, zinka22 commented on solutions/pytest_folder/test_parametrization.py
> +    user_is_authorized = check_if_user_is_authorized(browser)
там больше не нужна эта переменная, пока на паузу. Статью прочла

2024-06-27 18:37 UTC, zinka22 commented on solutions/pytest_folder/test_parametrization.py
> +    # проверка, авторизован ли пользователь
убрала

2024-06-27 18:40 UTC, zinka22 commented on solutions/pytest_folder/test_parametrization.py
> +        assert (
просрочила, добавила руками

2024-06-28 08:37 UTC, Cliffart44 requested changes

2024-06-28 08:37 UTC, Cliffart44 commented on helpers.py
> +            return popup_is_closed
А что она возвращает?

2024-06-28 08:37 UTC, Cliffart44 commented on solutions/pytest_folder/test_parametrization.py
> +            pass
ОК, тогда пусть остаётся так 🙂

2024-06-28 08:37 UTC, Cliffart44 commented on tasks/test_parametrization.md
> +_______________________________
Тогда ж и тут https://github.com/zinka22/Selenium-cource/pull/41#discussion_r1656561518 нужно.
```suggestion
---
```

2024-06-28 08:37 UTC, Cliffart44 commented on helpers.py
> +def check_if_user_is_authorized(browser):
Тут точно есть смысл делать отдельную функцию для этого, а не выполнять всё в `assert_if_user_is_authorized`? Если да, то...

```suggestion
def _check_if_user_is_authorized(browser):
```

2024-06-28 10:20 UTC, Cliffart44 commented on solutions/pytest_folder/test_parametrization.py
> +    enter_button = browser.find_element(By.CLASS_NAME, "navbar__auth_login ")
```suggestion
    enter_button = browser.find_element(By.CLASS_NAME, "navbar__auth_login")
```

2024-06-29 07:24 UTC, Cliffart44 commented on helpers.py
> +def check_if_user_is_authorized(browser):
И создай, пожалуйста, Issue насчёт обновления проверки авторизации в соседнем тесте и назначь меня исполнителем 😉

2024-06-29 18:48 UTC, zinka22 commented on helpers.py
> +            return popup_is_closed
true/false возвращает

сразу true надо было писать) так прямо точно понятнее

2024-06-29 19:12 UTC, zinka22 commented on helpers.py
> +def check_if_user_is_authorized(browser):
итого отдельную функцию убрала, добавила проверку на закрытие попапа в assert function

2024-06-29 19:16 UTC, zinka22 commented on helpers.py
> +def check_if_user_is_authorized(browser):
сделала задачу, #44

2024-06-29 19:31 UTC, Cliffart44 commented on helpers.py
> +            return popup_is_closed
[Документация](https://www.selenium.dev/selenium/docs/api/py/webdriver_support/selenium.webdriver.support.expected_conditions.html#selenium.webdriver.support.expected_conditions.invisibility_of_element_located) 😉

2024-06-29 19:40 UTC, Cliffart44 approved these changes
Оставшееся лишнее в #44 уйдёт 😉

2024-06-29 19:41 UTC, merged