Задание: добавление в корзину со страницы товара (task_add_to_cart)
zinka22/Selenium-cource pull request #50
Opened 2024-07-12 18:12 UTC by zinka22

1) тут добавила папку page_object с файлами из курса (шли установочные шаги с пояснениями, как работает и в них отрезки кода с потребностью дописать методы). Файлы: base_page.py, locators.py, login_page.py, main_page.py, test_items.py, test_main_page.py
2) решение задачи - product_page.py и test_product_page.py

На момент 12.07 21:12: запускается, дает правильный ответ для баллов в курсе, ничего не проверяет.

2024-07-15 16:34 UTC, Cliffart44 requested changes
В целом большая работа, конечно, проделана. Уже пошёл другой уровень автоматизации тестирования 😉

2024-07-15 16:34 UTC, Cliffart44 commented on solutions/page_object/pages/base_page.py
> +    def is_element_present(self, how, what):
...читаю код: "Функция «Элемент присутствует» с параметрами «как» и «что»". «Как» что и что «что»?

2024-07-15 16:34 UTC, Cliffart44 commented on tasks/test_product_page.md
> +   ```solve_quiz_and_get_code()```, который приведен ниже. Например, можете добавить его в класс BasePage, чтобы
```suggestion
   `solve_quiz_and_get_code()`, который приведен ниже. Например, можете добавить его в класс BasePage, чтобы
```

2024-07-15 16:34 UTC, Cliffart44 commented on tasks/test_product_page.md
> +Для этого вам нужно:
```suggestion
**Тест нужно написать, используя паттерн Page Object.** Для этого вам нужно:
```

2024-07-15 16:34 UTC, Cliffart44 commented on tasks/test_product_page.md
> +   использовать его на любой странице. Этот
Тут странный перенос строки.

2024-07-15 16:34 UTC, Cliffart44 commented on tasks/test_product_page.md
> +   товара (http://selenium1py.pythonanywhere.com/catalogue/the-shellcoders-handbook_209/?promo=newYear).
```suggestion
1) Открыть страницу товара
   (http://selenium1py.pythonanywhere.com/catalogue/the-shellcoders-handbook_209/?promo=newYear).
```

2024-07-15 16:34 UTC, Cliffart44 commented on tasks/test_product_page.md
> +   описывать конкретную реализацию.
```suggestion
   потом описывать конкретную реализацию.
```

2024-07-15 16:34 UTC, Cliffart44 commented on solutions/page_object/test_product_page.py
> +def test_guest_can_add_product_to_basket(browser):
Не смог запустить таким образом:

```bash
pytest -s solutions/page_object/test_product_page.py --browser_name=fierfox
```

Получаю

```bash
========================================================================= short test summary info ========================================================================= 
ERROR solutions/page_object/test_product_page.py::test_guest_can_add_product_to_basket - AttributeError: 'NoneType' object has no attribute 'implicitly_wait'
```

В чём может быть причина?

2024-07-15 16:34 UTC, Cliffart44 commented on solutions/page_object/pages/base_page.py
> +        x = alert.text.split(" ")[2]
Понятно, что скопировано, но это здесь явно лишнее.

```suggestion
        x = alert.text.split()[2]
```

2024-07-15 16:34 UTC, Cliffart44 commented on solutions/page_object/pages/base_page.py
> +            print(f"Your code: {alert_text}")
Такое в автотестах вряд ли будет встречаться, но в учебном проекте, наверное, так проще всего.

2024-07-15 16:34 UTC, Cliffart44 commented on solutions/page_object/pages/locators.py
> +    LOGIN_LINK = (By.ID, "login_link")
Почему tuples, если не секрет? 🙂

2024-07-15 16:34 UTC, Cliffart44 commented on solutions/page_object/pages/product_page.py
> +        button_add_to_cart = self.is_element_present(*ProductPageLocators.ADD_TO_CART)
Не лучше ли распаковывать сразу в `is_element_present`? Заодно проще будет параметр функции назвать.

```suggestion
        button_add_to_cart = self.is_element_present(ProductPageLocators.ADD_TO_CART)
```

2024-07-15 16:34 UTC, Cliffart44 commented on solutions/page_object/pages/product_page.py
> +        assert re.search(
Здесь можно без `re` обойтись, но если хочется, то можно и так 😆

2024-07-15 16:34 UTC, Cliffart44 commented on solutions/page_object/test_items.py
> +    browser.get("http://selenium1py.pythonanywhere.com/catalogue/coders-at-work_207/")
В описании указан другой адрес. А что это вообще за тест?

2024-07-15 16:34 UTC, Cliffart44 commented on solutions/page_object/test_main_page.py
> +
Не нашёл этого в описании. А что это вообще за тесты?

2024-07-16 13:07 UTC, zinka22 commented on solutions/page_object/pages/locators.py
> +    LOGIN_LINK = (By.ID, "login_link")
что почитала: 
* неизменяемый тип, важно для локатора
* занимает меньше памяти чем список
возможно нужно углубиться. Нужно?

2024-07-16 13:07 UTC, zinka22 commented on solutions/page_object/pages/product_page.py
> +        button_add_to_cart = self.is_element_present(*ProductPageLocators.ADD_TO_CART)
сделала

2024-07-16 13:09 UTC, zinka22 commented on solutions/page_object/pages/base_page.py
> +    def is_element_present(self, how, what):
тут изменила на locator и стала распаковывать в функции

долго билась с распаковкой. если locator не ок, подумаю еще

2024-07-16 13:11 UTC, zinka22 commented on solutions/page_object/pages/product_page.py
> +        assert re.search(
хочу re. Неделю одну задачу решала, дань памяти так сказать. Хоть где то пригодилось)

но если лучше нет то не, не спорю

2024-07-16 13:12 UTC, zinka22 commented on solutions/page_object/test_items.py
> +    browser.get("http://selenium1py.pythonanywhere.com/catalogue/coders-at-work_207/")
на код "вспомогательный" который был добавлен копипастой сделаю описание, в следующем комите

2024-07-17 09:39 UTC, Cliffart44 commented on solutions/page_object/pages/locators.py
> +    LOGIN_LINK = (By.ID, "login_link")
Пока не обязательно, просто было интересно основание выбора.

2024-07-17 09:41 UTC, Cliffart44 commented on solutions/page_object/pages/product_page.py
> +        assert re.search(
Часто в программировании одну и ту же задачу можно решить различными способами, и это хорошо, если нет откровенных перекосов. Здесь нет, так что можно и так 🙂

2024-07-17 12:46 UTC, Cliffart44 requested changes

2024-07-17 12:46 UTC, Cliffart44 commented on solutions/page_object/pages/base_page.py
> +    def is_element_present(self, how, what):
В целом можно и так. По крайней мере, этот код единожды теперь прописан.

2024-07-17 18:13 UTC, zinka22 commented on tasks/test_product_page.md
> +   использовать его на любой странице. Этот
отформатировала

2024-07-17 18:51 UTC, zinka22 commented on solutions/page_object/test_product_page.py
> +def test_guest_can_add_product_to_basket(browser):
добавила ожидание в base_page и дефолтное значение языка в сonftest. С firefox работает.

в твоем запросе на запуск теста опечатка в firefox, если запускать pytest -s solutions/page_object/test_product_page.py --browser_name=firefox
 ошибки нет (а AttributeError: 'NoneType' object has no attribute 'implicitly_wait' видимо оттого что браузер не запустился)

2024-07-17 19:13 UTC, zinka22 commented on solutions/page_object/test_main_page.py
> +
тут трудно

файлы base_page, main_page и ее тест, login page были добавлены где-то копипастой, где-то дописывались методы проверок.
итого 9 страниц добавлений и до этого 9 страниц объяснений.
![image](https://github.com/user-attachments/assets/bb693280-6fee-4aad-90a9-caa88cd46d31)
думаю как компактно описать, чтобы не читать долго. Пока решения нет.

2024-07-18 19:01 UTC, zinka22 commented on solutions/page_object/test_main_page.py
> +
сделала

2024-07-18 19:01 UTC, zinka22 commented on solutions/page_object/test_items.py
> +    browser.get("http://selenium1py.pythonanywhere.com/catalogue/coders-at-work_207/")
это дублер, был реализован в #47

2024-07-19 13:51 UTC, Cliffart44 requested changes
И ещё добавлю сейчас pull request.

2024-07-19 13:51 UTC, Cliffart44 commented on solutions/page_object/test_product_page.py
> +def test_guest_can_add_product_to_basket(browser):
Теперь падает с 
```bash
========================================================================= short test summary info ========================================================================= 
FAILED solutions/page_object/test_product_page.py::test_guest_can_add_product_to_basket - selenium.common.exceptions.TimeoutException: Message:
=========================================================================== 1 failed in 26.06s ============================================================================ 
```

Что не так?

---

Всё верно, там опечатка, и по сообщению об ошибке это совсем не понятно. Может быть, стоит добавить валидацию ввода?

2024-07-19 13:51 UTC, Cliffart44 commented on tasks/test_main_page.md
> +def test_guest_can_go_to_login_page(browser):
Стоит разместить код так, чтобы не ломать структуру списка ([документация](https://www.markdownguide.org/basic-syntax/#code-blocks-1)) в том числе и в PyCharm — сделаю сам, всё равно читаю.

2024-07-19 13:51 UTC, Cliffart44 commented on tasks/test_product_page.md
> +
```suggestion


```

2024-07-19 13:51 UTC, Cliffart44 commented on tasks/test_product_page.md
> +```
```suggestion
```python
import math

```

2024-07-19 13:51 UTC, Cliffart44 commented on solutions/page_object/pages/base_page.py
> +from selenium.webdriver.support import expected_conditions as EC
![image](https://github.com/user-attachments/assets/72d41cf9-957a-4e8f-a15b-825635442df2)

2024-07-19 13:51 UTC, Cliffart44 commented on tasks/test_product_page.md
> +pytest -s test_foo.py
```suggestion
```shell
pytest -s test_product_page.py
```

2024-07-21 16:23 UTC, zinka22 commented on solutions/page_object/test_product_page.py
> +def test_guest_can_add_product_to_basket(browser):
сделала проверку на ввод 
![image](https://github.com/user-attachments/assets/76523b37-5e01-41ed-95ac-103634b6a08f)

2024-07-21 17:57 UTC, zinka22 commented on solutions/page_object/test_product_page.py
> +def test_guest_can_add_product_to_basket(browser):
по вопросу с сообщением оtimeout exception тоже добавила

2024-07-21 18:05 UTC, zinka22 commented on solutions/page_object/pages/base_page.py
> +from selenium.webdriver.support import expected_conditions as EC
сделала

2024-07-22 10:37 UTC, Cliffart44 requested changes

2024-07-22 10:37 UTC, Cliffart44 commented on solutions/page_object/pages/base_page.py
> +from selenium.webdriver.support import expected_conditions as EC
![image](https://github.com/user-attachments/assets/4ca4a62c-a4e9-4583-99d3-e1a4dc26b8f1)

И ещё автоформатирование есть смысл применить 🙂

2024-07-22 10:37 UTC, Cliffart44 commented on solutions/page_object/test_product_page.py
> +def test_guest_can_add_product_to_basket(browser):
Теперь падает с 

```bash
========================================================================= short test summary info ========================================================================= 
FAILED solutions/page_object/test_product_page.py::test_guest_can_add_product_to_basket - Failed: TimeoutException: Element second alert was not located in timeout time    
=========================================================================== 1 failed in 27.68s ============================================================================ 
```

Тест и должен падать?

2024-07-22 10:37 UTC, Cliffart44 commented on solutions/page_object/pages/base_page.py
> +        except NoAlertPresentException:
В каком случае может произойти такая исключительная ситуация?

2024-07-22 10:37 UTC, Cliffart44 commented on solutions/page_object/conftest.py
> +    if browser_name == "chrome":
И тут всё таки рекомендовал бы использовать [Structural Pattern Matching](https://docs.python.org/3/tutorial/controlflow.html#match-statements), поскольку особо ничего дорабатывать не придётся (также можно создать отдельную issue для этого).

2024-07-22 18:56 UTC, zinka22 commented on solutions/page_object/pages/base_page.py
> +from selenium.webdriver.support import expected_conditions as EC
сделала настройку 
![image](https://github.com/user-attachments/assets/f2026302-1ba8-453a-a4de-6582e401ccc7)

2024-07-22 19:04 UTC, zinka22 commented on solutions/page_object/test_product_page.py
> +def test_guest_can_add_product_to_basket(browser):
Нет, на времени падать не должен. Тут произошло расширение задачи:  постановки на написание теста на firefox в задаче курса не было (т.е. то что он через раз падает там где не планировали проверять возможно ок). Для Chrome, например, нет потребности в ожидании alert, а для firefox есть. 
Я пока думала как сделать чтобы падал примерно через раз (а иногда через пять раз) ставила ожидание 1 секунду. На 10 вообще не ловится падение

Если тут ошибка и я не вижу, намекни.

2024-07-22 19:05 UTC, zinka22 commented on solutions/page_object/pages/base_page.py
> +        except NoAlertPresentException:
тут копипаста с задачи.

Есть TimeoutException покрывает эту проверку. Убрать?

2024-07-22 19:13 UTC, zinka22 commented on solutions/page_object/conftest.py
> +    if browser_name == "chrome":
#52 
плохо вникла что нужно сделать, посмотри постановку, пожалуйста.

Нужно почитать по ссылке (оставила) и почитать статьи по теме. Быстро не сообразила)

2024-07-23 11:37 UTC, Cliffart44 commented on solutions/page_object/conftest.py
> +    if browser_name == "chrome":
Ну, уже не забудется, так что пойдёт.

2024-07-23 17:36 UTC, Cliffart44 requested changes

2024-07-23 17:36 UTC, Cliffart44 commented on solutions/page_object/pages/base_page.py
> +        except NoAlertPresentException:
Да, иначе получается ожидание того, что никогда не наступит.

2024-07-23 17:36 UTC, Cliffart44 commented on solutions/page_object/pages/base_page.py
> +from selenium.webdriver.support import expected_conditions as EC
А `git push` сделала?

2024-07-23 17:36 UTC, Cliffart44 commented on solutions/page_object/test_product_page.py
> +def test_guest_can_add_product_to_basket(browser):
У меня ни разу на Firefox не запустился тест просто. При этом ты заявляешь возможность запускать его в этом браузере. Поэтому нужно либо довести до ума Firefox, либо заменить его на Edge, либо оставить один Chrome. Я бы предложил компромиссный второй вариант.

2024-07-26 18:13 UTC, zinka22 commented on solutions/page_object/pages/base_page.py
> +from selenium.webdriver.support import expected_conditions as EC
нет конечно)теперь сделала

2024-07-26 18:15 UTC, zinka22 commented on solutions/page_object/pages/base_page.py
> +        except NoAlertPresentException:
убрала

2024-07-26 18:40 UTC, zinka22 commented on solutions/page_object/test_product_page.py
> +def test_guest_can_add_product_to_basket(browser):
добавила edge, изменила дефолтный язык у firefox

кажется, что на firefox может запуститься. Попробуй с ним тоже, пожалуйста

2024-07-27 18:32 UTC, Cliffart44 commented on solutions/page_object/test_product_page.py
> +def test_guest_can_add_product_to_basket(browser):
Ну, язык сменила для всех браузеров. Но да, теперь работает 🙂

2024-07-27 18:32 UTC, Cliffart44 commented on solutions/page_object/conftest.py
> +    elif browser_name == "edge":
А почему для него язык не учитываешь?

2024-07-27 18:36 UTC, Cliffart44 commented on solutions/page_object/pages/base_page.py
> +)
Кстати, тут проще теперь можно, если хочешь.

```suggestion
from selenium.common.exceptions import NoSuchElementException, TimeoutException
```

2024-07-27 18:43 UTC, zinka22 commented on solutions/page_object/conftest.py
> +    elif browser_name == "edge":
Первые два браузера с языком, т.к. было задание, в котором тесты запускались с указанием языка в параметрах.

Т.е. ля Chrome, Firefox язык используется в другом тесте и поэтому остался прописан. Для этого теста постановки указывать язык не было, поэтому для третьего браузера опцию не добавила.

Вообще и запуск в браузере, отличном от Chrome в постановке тоже не стоял. Если лучше единообразно сделать, добавлю язык.

2024-07-27 18:46 UTC, zinka22 commented on solutions/page_object/test_product_page.py
> +def test_guest_can_add_product_to_basket(browser):
в задании про локаль написан язык по дефолту en. Кажется, что сайт с ru работает плохо (гипотеза). Поменяла на en, сработало)

2024-07-27 19:03 UTC, Cliffart44 commented on solutions/page_object/conftest.py
> +    elif browser_name == "edge":
Да, давай и готово 🎉

2024-07-27 20:54 UTC, zinka22 commented on solutions/page_object/conftest.py
> +    elif browser_name == "edge":
сделала, 10 минут проверю еще

2024-07-28 04:15 UTC, Cliffart44 approved these changes

2024-07-28 04:18 UTC, merged