Задание: негативные проверки (task_negative_tests)
zinka22/Selenium-cource pull request #53
Opened 2024-07-29 07:11 UTC by zinka22

тут добавила:
1) логику в base_page.py
2) логику в product_page.py
3) тесты в test_product_page.py
4) локатор в locators.py
5) задание в md файл
6) ссылку на задание и реализацию в test_product_page.py
7) закомментировала неявные ожидания в conftest и base_page

2024-07-29 13:17 UTC, Cliffart44 requested changes

2024-07-29 13:17 UTC, Cliffart44 commented on solutions/page_object/conftest.py
> +    # browser.implicitly_wait(15)
В целом закомментированного кода в `main` быть не должно. Если без этого действительно никак, то нужен комментарий с пояснениями о том, для чего именно этот код оставлен и в каких именно случаях он комментируется.

2024-07-29 13:17 UTC, Cliffart44 commented on solutions/page_object/pages/base_page.py
> +            )
Не будет ли так проще читаться?

```suggestion
            )
            return False
```

2024-07-29 13:17 UTC, Cliffart44 commented on solutions/page_object/test_product_page.py
> +    link = "http://selenium1py.pythonanywhere.com/catalogue/the-shellcoders-handbook_209/?promo=newYear"
Ссылку есть смысл вынести в переменную и указать её с `https`.

2024-08-03 18:26 UTC, zinka22 commented on solutions/page_object/conftest.py
> +    # browser.implicitly_wait(15)
С комментированием кажется есть загвоздка: ранее задачи выполнялись с использованием неявного ожидания, а в этом задании неявные ожидания стали мешать. 
Т.е. получается, что это условие нужно для негативных проверок и не нужно для функциональных, которые были раньше.
"Закомментируйте неявные ожидания" - постановка спущена с задачи курса.

Проверила - без неявного ожидания - работает. Если без него работает может уберу?

2024-08-03 18:49 UTC, zinka22 commented on solutions/page_object/test_product_page.py
> +    link = "http://selenium1py.pythonanywhere.com/catalogue/the-shellcoders-handbook_209/?promo=newYear"
сделала

2024-08-08 06:51 UTC, Cliffart44 requested changes

2024-08-08 06:51 UTC, Cliffart44 commented on solutions/page_object/conftest.py
> +    # browser.implicitly_wait(15)
Так работают и уже имеющиеся тесты, и новые?
Тогда возникает вопрос: а зачем вообще изначально добавлялись неявные ожидания?

Как правило, менять уже имеющуюся логику работы тестов при создании новых не следует — для этого лучше создавать отдельную задачу.

Нельзя ли, если ожидания не нужны, передавать туда `0` из тех тестов, где они не нужны? При этом уже имеющиеся тесты будут работать по-прежнему.

---
Кстати, не вижу в задании этого:
> "Закомментируйте неявные ожидания" - постановка спущена с задачи курса.

А ещё...
> в этом задании неявные ожидания стали мешать.

...у меня и с ожиданиями тесты работают. Так не должно быть?

2024-08-08 06:51 UTC, Cliffart44 commented on solutions/page_object/pages/base_page.py
> +            )
https://github.com/zinka22/Selenium-cource/pull/53#discussion_r1695148525

2024-08-08 07:47 UTC, zinka22 commented on solutions/page_object/conftest.py
> +    # browser.implicitly_wait(15)
перечитала постановку. Напрямую закомментировать не писали, это я неверно интерпретировала.

Если правильно поняла, там имели ввиду, что отрицательные проверки на 10-15 секундном ожидании делать долго и неудобно, поэтому в отрицательных пропишем явные ожидания.
И теперь на тестах стоит неявное ожидание, а на отрицательных прописано явное (и когда идет прогон, явное ожидание побеждает и в неявное не смотрит)
___
1) правильно поняла? 
2) в тесте одновременно и явные и неявные. Так можно?

2024-08-08 07:54 UTC, zinka22 commented on solutions/page_object/pages/base_page.py
> +            )
сделала

2024-08-08 09:56 UTC, zinka22 commented on solutions/page_object/conftest.py
> +    # browser.implicitly_wait(15)
нашла, откуда "приехала" строка с неявным ожиданием: 
![image](https://github.com/user-attachments/assets/f81efcc3-01ef-4a42-9497-6be5f283078f)

не могу прямо точно найти, но, кажется, добавила 10 секунд при параметризации для разных браузеров (конкретно для firefox)

Кажется для conftest.py и base_page.py можно попробовать убрать строки с implicitly_wait и проверить все тесты в page object папочке, что без него работает.
#54

2024-08-08 10:05 UTC, Cliffart44 requested changes

2024-08-08 10:05 UTC, Cliffart44 commented on solutions/page_object/pages/base_page.py
>          return True
Теперь и для этого issue нужна по мотивам https://github.com/zinka22/Selenium-cource/pull/53#discussion_r1695148525.

2024-08-08 10:05 UTC, Cliffart44 commented on solutions/page_object/pages/base_page.py
> +        # self.browser.implicitly_wait(timeout)
```suggestion
        self.browser.implicitly_wait(timeout)
```

2024-08-08 10:05 UTC, Cliffart44 commented on solutions/page_object/conftest.py
> +base_shop_url = "https://selenium1py.pythonanywhere.com/catalogue/the-shellcoders-handbook_209/?promo=newYear"
Кстати, почему бы не размесить ссылку в `solutions/page_object/test_product_page.py`, где она и используется? Или есть какая-то причина держать её тут?

2024-08-08 10:05 UTC, Cliffart44 commented on solutions/page_object/conftest.py
> +    # browser.implicitly_wait(15)
> ___
> 1) правильно поняла? 
> 2) в тесте одновременно и явные и неявные. Так можно?


Ну, скажем так, ответ на оба вопроса есть в [документации](https://www.selenium.dev/documentation/webdriver/waits/).

---
> Нельзя ли, если ожидания не нужны, передавать туда 0 из тех тестов, где они не нужны? При этом уже имеющиеся тесты будут работать по-прежнему.

Давай в solutions/page_object/pages/product_page.py добавим

```python
    def __init__(self, browser, url, timeout=10):
        super().__init__(browser, url, timeout)
```

Тогда из нужных тестов можно будет

```python
    page = ProductPage(browser, base_shop_url, timeout=implicit_wait_default_value)
```

2024-08-08 10:13 UTC, Cliffart44 commented on solutions/page_object/conftest.py
> +    # browser.implicitly_wait(15)
По поводу #54 — 🆗, но заниматься этим будет лучше уже после текущей задачи.

2024-08-08 10:18 UTC, zinka22 commented on solutions/page_object/pages/base_page.py
>          return True
задача или тут поправить чтобы одинаково было?

2024-08-08 10:27 UTC, Cliffart44 commented on solutions/page_object/pages/base_page.py
>          return True
Строго говоря, нужна отдельная, но две строки можно и тут исправить 🙂

2024-08-15 11:28 UTC, zinka22 commented on solutions/page_object/conftest.py
> +    # browser.implicitly_wait(15)
сделала как в комментарии выше

2024-08-15 11:32 UTC, zinka22 commented on solutions/page_object/conftest.py
> +base_shop_url = "https://selenium1py.pythonanywhere.com/catalogue/the-shellcoders-handbook_209/?promo=newYear"
перенесла

2024-08-15 11:36 UTC, zinka22 commented on solutions/page_object/pages/base_page.py
>          return True
сделала

2024-08-15 14:54 UTC, Cliffart44 requested changes
Всё, последние штрихи 🙂

2024-08-15 14:54 UTC, Cliffart44 commented on solutions/page_object/pages/product_page.py
> +        super().__init__(browser, url, timeout)
Лучше перенести в начало класса.

2024-08-15 14:54 UTC, Cliffart44 commented on solutions/page_object/test_product_page.py
> +
```suggestion
implicit_wait_default_value = 0

```

2024-08-15 14:54 UTC, Cliffart44 commented on solutions/page_object/test_product_page.py
> +    page = ProductPage(browser, base_shop_url, timeout=0)
Здесь и далее.
```suggestion
    page = ProductPage(browser, base_shop_url, timeout=implicit_wait_default_value)
```

2024-08-16 18:29 UTC, zinka22 commented on solutions/page_object/pages/product_page.py
> +        super().__init__(browser, url, timeout)
сделала

2024-08-16 18:33 UTC, zinka22 commented on solutions/page_object/test_product_page.py
> +    page = ProductPage(browser, base_shop_url, timeout=0)
сделала. Теперь поняла, откуда было ..., timeout=implicit_wait_default_value) ... именно в таком виде

2024-08-16 19:21 UTC, Cliffart44 requested changes

2024-08-16 19:21 UTC, Cliffart44 commented on solutions/page_object/test_product_page.py
> +    page = ProductPage(browser, base_shop_url, timeout=0)
https://github.com/zinka22/Selenium-cource/pull/53#discussion_r1718517225

2024-08-16 19:21 UTC, Cliffart44 commented on solutions/page_object/test_product_page.py
> +    page = ProductPage(browser, base_shop_url, timeout=0)
https://github.com/zinka22/Selenium-cource/pull/53#discussion_r1718517225

2024-08-19 18:21 UTC, zinka22 commented on solutions/page_object/test_product_page.py
> +    page = ProductPage(browser, base_shop_url, timeout=0)
сделала

2024-08-19 18:21 UTC, zinka22 commented on solutions/page_object/test_product_page.py
> +    page = ProductPage(browser, base_shop_url, timeout=0)
сделала

2024-08-19 18:25 UTC, Cliffart44 approved these changes

2024-08-19 18:27 UTC, merged