Задание: плюсы наследования, пример (task_inheritance_negative_tests)
zinka22/Selenium-cource pull request #55
Opened 2024-08-20 19:56 UTC by zinka22

Тут в соответствие с задачей:
1) перенесла логику из main_page.py в base_page.py
2) добавила в locators.py класс BasePageLocators и перенесла туда элементы из MainPageLocators (с поправкой: в задании есть корректный и некорректный локатор, для теста)
3) в классе MainPage добавила заглушку
4) в test_product_page.py добавила 2 теста - из main (один скопировала из примера, один из main_page)

2024-08-23 07:50 UTC, Cliffart44 requested changes
👨‍💻

2024-08-23 07:50 UTC, Cliffart44 commented on tasks/task_inheritance_test_negative.md
> +В предыдущем уроке, мы написали тест "гость может перейти на страницу логина с главной страницы магазина". Но если вы
```suggestion
В предыдущем уроке мы написали тест "Гость может перейти на страницу логина с главной страницы магазина". Но если вы
```

2024-08-23 07:50 UTC, Cliffart44 commented on tasks/task_inheritance_test_negative.md
> +LOGIN_LINK = (By.CSS_SELECTOR, "#login_link")
Здесь и далее в аналогичных местах нужно привести в порядок отступы.

2024-08-23 07:50 UTC, Cliffart44 commented on tasks/task_inheritance_test_negative.md
> +Как вы уже знаете, метод __init__ вызывается при создании объекта. Конструктор выше с ключевым словом super на самом
```suggestion
Как вы уже знаете, метод `__init__` вызывается при создании объекта. Конструктор выше с ключевым словом `super` на самом
```

2024-08-23 07:50 UTC, Cliffart44 commented on tasks/task_inheritance_test_negative.md
> +Запустите тесты и убедитесь, что они проходят.
```suggestion
Добавьте самостоятельно второй тест `test_guest_can_go_to_login_page_from_product_page`. Запустите тесты и убедитесь,
что они проходят.
```

2024-08-23 07:50 UTC, Cliffart44 commented on solutions/page_object/pages/locators.py
> +
```suggestion
```

2024-08-23 07:50 UTC, Cliffart44 commented on solutions/page_object/pages/main_page.py
2 строка не используется.

2024-08-23 07:50 UTC, Cliffart44 commented on solutions/page_object/pages/base_page.py
> -    def open(self):
Правильно понимаю, что методы здесь были отсортированы по алфавиту? Если да, то это хорошо, но давай отдельную Issue для этого, и такой Pull request нужно будет слить перед текущим.

---
Кстати, что там с двумя уже имеющимися Issues, есть планы на выполнение? 🙂

2024-08-23 07:50 UTC, Cliffart44 commented on tasks/task_inheritance_test_negative.md
> +Теперь мы можем легко добавлять тесты вида "гость может перейти на страницу логина со страницы Х".
```suggestion
Теперь мы можем легко добавлять тесты вида "Гость может перейти на страницу логина со страницы Х".
```

2024-08-23 07:50 UTC, Cliffart44 commented on solutions/page_object/test_product_page.py
> +def test_guest_can_go_to_login_page_from_product_page(browser):
У меня тест падает на
```shell
>       page.go_to_login_page()
```
с `NoSuchElementException`. Как-то не так запускаю?

2024-08-24 13:09 UTC, zinka22 commented on solutions/page_object/pages/base_page.py
> -    def open(self):
вернула не по алфавиту.
два issue сделаю, я ленилась и делала вид, что их нет. Выглядят страшно, трудно подступиться в общем.

2024-08-24 14:23 UTC, zinka22 commented on tasks/task_inheritance_test_negative.md
> +LOGIN_LINK = (By.CSS_SELECTOR, "#login_link")
сделала

2024-08-24 14:25 UTC, zinka22 commented on solutions/page_object/pages/main_page.py
убрала

2024-08-24 14:27 UTC, zinka22 commented on solutions/page_object/test_product_page.py
> +def test_guest_can_go_to_login_page_from_product_page(browser):
строка 65 в base_page стоит локатор LOGIN_LINK_INVALID. Из задачи, был для проверки, что тест падает.
Стерла INVALID, должен проходить (смотрит на верный локатор)

2024-08-25 17:14 UTC, Cliffart44 commented on solutions/page_object/pages/base_page.py
> -    def open(self):
> это хорошо, но давай отдельную Issue для этого, и такой Pull request нужно будет слить перед текущим.

Как раз для того, чтобы не делать одно и то же по нескольку раз. Но можно сделать и несколько раз, конечный результат от этого не пострадает 🙂

---
> Выглядят страшно, трудно подступиться в общем.

Страшно охватить всю глубину сходу. А сделать необходимое в том контексте — вполне по силам, как видишь 😉

2024-08-26 14:41 UTC, Cliffart44 requested changes

2024-08-26 14:41 UTC, Cliffart44 commented on tasks/task_inheritance_test_negative.md
> +
```suggestion


```

2024-08-26 14:41 UTC, Cliffart44 commented on tasks/task_inheritance_test_negative.md
> +class MainPage(BasePage):
```suggestion
class MainPage(BasePage):

```

2024-08-26 14:41 UTC, Cliffart44 commented on solutions/page_object/pages/locators.py
> +    LOGIN_LINK_INVALID = (By.CSS_SELECTOR, "#login_link_inc")
Нигде теперь не используется, но дважды упоминается в tasks/task_inheritance_test_negative.md. Есть смысл добавить пояснение и тут, и там, зачем это нужно.

Ну либо просто удалить неиспользуемый код 🙂

2024-08-26 14:41 UTC, Cliffart44 commented on solutions/page_object/test_product_page.py
> +def test_guest_can_go_to_login_page_from_product_page(browser):
https://github.com/zinka22/Selenium-cource/pull/55#discussion_r1731353124

2024-08-26 14:42 UTC, Cliffart44 commented on solutions/page_object/pages/base_page.py
> +
А здесь теперь стало хорошо видно, что добавилось два метода — юлагодаря выносу рефакторинга по сортировке в отдельный pull request.

2024-08-28 18:30 UTC, zinka22 commented on solutions/page_object/pages/locators.py
> +    LOGIN_LINK_INVALID = (By.CSS_SELECTOR, "#login_link_inc")
убрала из locators.py и task_inheritance_test_negative.md 

образовательную функцию этот локатор выполнил)

2024-08-29 07:10 UTC, Cliffart44 approved these changes

2024-08-29 07:10 UTC, merged