Задание: группировка тестов и setup
zinka22/Selenium-cource pull request #59
Opened 2024-09-09 18:31 UTC by zinka22

<дополняется>

1) сделана группировка тестов в test_main_page и test_product_page (имеющиеся тесты собраны в классы)
2) на классы с тестами добавлена маркировка для запуска pytest
3) добавлен файл pytest.ini для регистрации маркировки

2024-09-25 13:47 UTC, Cliffart44 requested changes
Что-то я напоследок... 😅

2024-09-25 13:47 UTC, Cliffart44 commented on README.md
> +|              [Группировка тестов и setup](tasks/task_grouping_and_setup.md)              |              [test_product_page](solutions/page_object/test_product_page.py)              |
Почему-то сбита сортировка, исправь тут или отдельно. До `tasks/switch_to_window.md` порядок, а далее должны идти

```
tasks/task_grouping_and_setup.md
tasks/task_inheritance_test_negative.md
tasks/task_negative_tests.md
```

И после `tasks/test_authorization.md` тоже будет порядок.

P.S. [Так это делать очень удобно](https://www.jetbrains.com/guide/python/tips/move-block/).

2024-09-25 13:47 UTC, Cliffart44 commented on solutions/page_object/pytest.ini
> +    login_guest
Пожалуйста 😸

```suggestion
    login_guest

```

2024-09-25 13:47 UTC, Cliffart44 commented on tasks/task_grouping_and_setup.md
> +ВАЖНО! Вообще говоря манипулировать браузером в сетапе и уж тем более что-то там проверять — это плохая практика, лучше
```suggestion
ВАЖНО! Вообще говоря, манипулировать браузером в сетапе и уж тем более что-то там проверять — это плохая практика, лучше
```

2024-09-25 13:47 UTC, Cliffart44 commented on tasks/task_grouping_and_setup.md
> +   " probably unauthorised user"
```suggestion
       assert self.is_element_present(BasePageLocators.USER_ICON), (
           "User icon is not presented," " probably unauthorised user"
       )
```

2024-09-25 13:47 UTC, Cliffart44 commented on tasks/task_grouping_and_setup.md
> +5) добавьте в BasePage проверку того, что пользователь залогинен:
```suggestion
1) в файле test_product_page.py добавьте новый класс для тестов `TestUserAddToBasketFromProductPage`;
2) добавьте туда уже написанные тесты `test_guest_cant_see_success_message` и `test_guest_can_add_product_to_basket` и
   переименуйте, заменив `guest` на `user` (не меняйте шаги в тесте и не добавляйте параметризацию: тут добавится
   регистрация в начале);
3) добавьте в `LoginPage` метод `register_new_user(email, password)`, который принимает две строки и регистрирует
   пользователя;
4) реализуйте его, описав соответствующие элементы страницы;
5) добавьте в `BasePage` проверку того, что пользователь залогинен:
```

2024-09-25 13:47 UTC, Cliffart44 commented on tasks/task_grouping_and_setup.md
> +   Селектор соответственно в BasePageLocators:
```suggestion
   Селектор, соответственно, в `BasePageLocators`:
```

2024-09-25 13:47 UTC, Cliffart44 commented on tasks/task_grouping_and_setup.md
> +6) добавьте в класс фикстуру setup. В этой функции нужно:
```suggestion
6) добавьте в класс фикстуру `setup`. В этой функции нужно:
```

2024-09-25 13:47 UTC, Cliffart44 commented on tasks/task_grouping_and_setup.md
> +8) зафиксируйте изменения в репозитории коммитом с осмысленным сообщением
```suggestion
8) зафиксируйте изменения в репозитории коммитом с осмысленным сообщением.
```

2024-09-25 13:47 UTC, Cliffart44 commented on tasks/task_grouping_and_setup.md
> +один из вариантов, чтобы избежать повторения, использовать текущее время с помощью модуля time:
```suggestion
`yield` писать не нужно — пользователей удалять мы не умеем. Генерировать email адреса для пользователей можно
по-разному, один из вариантов, чтобы избежать повторения, использовать текущее время с помощью модуля `time`:
```

2024-09-25 13:47 UTC, Cliffart44 commented on tasks/task_grouping_and_setup.md
> +```
Код тут криво вставляется, поэтому
![image](https://github.com/user-attachments/assets/ec07b00d-3a6b-405b-8e0d-7dade7b0d107)

2024-09-25 13:47 UTC, Cliffart44 commented on tasks/task_grouping_and_setup.md
> +### Группировка тестов и setup
```suggestion
### Подзадание-копипаста [subtask](../tasks/subtask_grouping_and_setup.md)

### Группировка тестов и `setup`
```

2024-09-25 13:47 UTC, Cliffart44 commented on tasks/subtask_grouping_and_setup.md
> +Давайте например объединим в группу два теста в файле test_main_page.py и пометим его меткой login_guest:
```suggestion
тесты, связанные с одним компонентом, лежат в одном классе, а с помощью `pytest.mark` можно помечать сразу весь класс.
Основное правило такое: название класса должно начинаться с `Test`, чтобы PyTest смог его обнаружить и запустить.

Давайте, например, объединим в группу два теста в файле test_main_page.py и пометим его меткой `login_guest`:
```

2024-09-25 13:47 UTC, Cliffart44 commented on tasks/subtask_grouping_and_setup.md
> +           # реализация теста
На строках до и после тоже нужно убрать лишние отступы.

```suggestion
@pytest.mark.login_guest
class TestLoginFromMainPage():
    # не забываем передать первым аргументом self
    def test_guest_can_go_to_login_page(self, browser):
        # реализация теста

    def test_guest_should_see_login_link(self, browser):
        # реализация теста
```

2024-09-25 13:47 UTC, Cliffart44 commented on tasks/subtask_grouping_and_setup.md
> +Эти функции:
```suggestion
**Во-вторых**, для разных тест-кейсов можно выделять общие функции, чтобы не повторять код. Эти функции:
```

2024-09-25 13:47 UTC, Cliffart44 commented on tasks/subtask_grouping_and_setup.md
> +  и ```autouse=True```, что значит запускать автоматически без явного вызова фикстуры.
```suggestion
  сгенерированные в тесте данные. Такие функции реализуются с помощью фикстур. Чтобы функция запускалась автоматически
  перед каждым тест-кейсом, нужно пометить её как `@pytest.fixture` с параметрами `scope="function"`, что значит
  запускать на каждую функцию, и `autouse=True`, что значит запускать автоматически без явного вызова фикстуры.
```

2024-09-25 13:47 UTC, Cliffart44 commented on tasks/subtask_grouping_and_setup.md
> +           # дальше обычная реализация теста
На строках до и после тоже нужно убрать лишние отступы.

```suggestion
@pytest.mark.login
class TestLoginFromProductPage():
    @pytest.fixture(scope="function", autouse=True)
    def setup(self):
        self.product = ProductFactory(title = "Best book created by robot")
        # создаем по API
        self.link = self.product.link
        yield
        # после этого ключевого слова начинается teardown
        # выполнится после каждого теста в классе
        # удаляем те данные, которые мы создали
        self.product.delete()

    def test_guest_can_go_to_login_page_from_product_page(self, browser):
        page = ProductPage(browser, self.link)
        # дальше обычная реализация теста

    def test_guest_should_see_login_link(self, browser):
        page = ProductPage(browser, self.link)
        # дальше обычная реализация теста
```

2024-09-25 13:47 UTC, Cliffart44 commented on tasks/subtask_grouping_and_setup.md
> +написали вот такой тест-класс в файле test_product_page.py:
```suggestion
Мы уже немного говорили про независимость от контента. Идеальным решением было бы везде, где мы работаем со страницей
продукта, создавать новый товар в нашем интернет-магазине перед тестом и удалять по завершении теста. К сожалению, наш
интернет-магазин пока не имеет возможности создавать объекты по API, но в идеальном мире мы бы написали вот такой
тест-класс в файле test_product_page.py:
```

2024-09-25 13:47 UTC, Cliffart44 commented on solutions/page_object/pages/base_page.py
> +        )
А не проще ли так? Или в чём суть двух строк в assertion_message?

```suggestion
        assert self.is_element_present(
            BasePageLocators.USER_ICON
        ), "User icon is not presented, probably unauthorised user"
```

2024-09-25 13:47 UTC, Cliffart44 commented on solutions/page_object/pages/base_page.py
> +    def should_be_authorized_user(self):
Тут же всё отсортировано? Тогда не на своём месте стоит.

2024-09-25 13:47 UTC, Cliffart44 commented on solutions/page_object/pages/locators.py
> +    SUCCESS_REGISTER = (By.CLASS_NAME, "alertinner")
Может, стоит по алфавиту?

2024-09-25 13:47 UTC, Cliffart44 commented on solutions/page_object/pages/login_page.py
> +        assert is_success_registered, "Registration is failed"
А зачем здесь эта проверка?
[](https://www.browserstack.com/guide/findelement-in-selenium#:~:text=Throws%20NoSuchElementException%20if%20the%20element%20is%20not%20found)

2024-09-25 13:47 UTC, Cliffart44 commented on solutions/page_object/pages/login_page.py
> +    def register_new_user(self):
Лучше поместить в начале класса.

2024-09-25 13:47 UTC, Cliffart44 commented on solutions/page_object/test_main_page.py
Не нужно ли сюда также добавить ссылку на md из этого PR?

2024-09-25 13:47 UTC, Cliffart44 commented on solutions/page_object/test_product_page.py
> +login_page_url = "https://selenium1py.pythonanywhere.com/en-gb/accounts/login/"
Тоже можно по алфавиту, в принципе.

2024-09-29 17:15 UTC, zinka22 commented on solutions/page_object/pytest.ini
> +    login_guest
русские буквы?

2024-09-30 08:17 UTC, Cliffart44 requested changes

2024-09-30 08:17 UTC, Cliffart44 commented on README.md
> +|              [Группировка тестов и setup](tasks/task_grouping_and_setup.md)              |              [test_product_page](solutions/page_object/test_product_page.py)              |
@zinka22, теперь файл соответствует структуре
![image](https://github.com/user-attachments/assets/002e9951-eb4c-43c6-be32-7013dc51de96)

2024-09-30 08:17 UTC, Cliffart44 commented on tasks/subtask_grouping_and_setup.md
> +   ```
Здесь и далее — убрать leading whitespaces.

2024-09-30 12:45 UTC, Cliffart44 commented on solutions/page_object/pytest.ini
> +    login_guest
[Это](https://joachimschuster.de/posts/why-inserting-newline-at-the-end-of-file/) 😃

2024-10-02 19:41 UTC, zinka22 commented on solutions/page_object/pytest.ini
> +    login_guest
сделала настройку

2024-10-02 19:45 UTC, zinka22 commented on tasks/task_grouping_and_setup.md
> +```
сделала

2024-10-02 19:49 UTC, zinka22 commented on tasks/subtask_grouping_and_setup.md
> +           # реализация теста
вроде сделала, не уверена, что поняла

Лишние отступы оказались только у символов начала и окончания кода `

2024-10-02 19:53 UTC, zinka22 commented on solutions/page_object/pages/base_page.py
> +    def should_be_authorized_user(self):
переместила

2024-10-04 07:25 UTC, Cliffart44 requested changes
И ещё https://github.com/zinka22/Selenium-cource/pull/59#discussion_r1775267944.

2024-10-07 17:38 UTC, zinka22 commented on solutions/page_object/pages/login_page.py
> +        assert is_success_registered, "Registration is failed"
да, ты прав
там задвоилось: 1) проверка, что пользователь зарегистрирован
2) проверка, что пользователь авторизован

одним коммитом уберу

2024-10-07 18:17 UTC, zinka22 commented on solutions/page_object/pages/login_page.py
> +    def register_new_user(self):
перенесла

2024-10-07 18:36 UTC, zinka22 commented on solutions/page_object/test_main_page.py
добавила

2024-10-07 18:38 UTC, zinka22 commented on solutions/page_object/test_product_page.py
> +login_page_url = "https://selenium1py.pythonanywhere.com/en-gb/accounts/login/"
сделала

2024-10-08 18:07 UTC, Cliffart44 commented on solutions/page_object/test_main_page.py
Да, но это ссылка на общую задачу. Изменения конкретно этого файла описаны в subtask_grouping_and_setup.md. Не будет ли лучше сразу туда указывать (тем более, там есть ссылка на основное задание)?

2024-10-12 16:01 UTC, zinka22 commented on solutions/page_object/test_main_page.py
поправила [коммит](74e5968a29ddbbe0f57ae19a249dd8374f01a9d5)

2024-10-14 07:23 UTC, Cliffart44 approved these changes
🎉

2024-10-14 07:23 UTC, merged