Проанализировать возможность убрать implicitly_wait из задач с page_object  (issue_delete_implicitly_wait)
zinka22/Selenium-cource pull request #60
Opened 2024-09-25 20:02 UTC by zinka22

1) убрала implicitly wait из conftest.py, base_bage.py
2)убрала timeout из product_page.py (была доп. настройка в связи с ожиданием)
3) проверила
 pytest -s -q solutions/page_object/test_product_page.py --language=en --browser_name=edge
 pytest -s -q  solutions/page_object/test_product_page.py --language=es --browser_name=edge
 pytest -s -q solutions/page_object/test_product_page.py --language=fr --browser_name=edge

 pytest -s -q  solutions/page_object/test_product_page.py --language=en --browser_name=firefox
 pytest -s -q solutions/page_object/test_product_page.py --language=es --browser_name=firefox
 pytest -s -q solutions/page_object/test_product_page.py --language=fr --browser_name=firefox

 pytest -s -q solutions/page_object/test_product_page.py --language=en --browser_name=chrome
 pytest -s -q solutions/page_object/test_product_page.py --language=es --browser_name=chrome
 pytest -s -q solutions/page_object/test_product_page.py --language=fr --browser_name=chrome

pytest -s -q  solutions/page_object/test_main_page.py --language=en --browser_name=edge
 pytest -s -q  solutions/page_object/test_main_page.py --language=es --browser_name=edge
 pytest -s -q  solutions/page_object/test_main_page.py --language=fr --browser_name=edge

 pytest -s -q  solutions/page_object/test_main_page.py --language=en --browser_name=firefox
 pytest -s -q  solutions/page_object/test_main_page.py --language=es --browser_name=firefox
 pytest -s -q  solutions/page_object/test_main_page.py --language=fr --browser_name=firefox

 pytest -s -q  solutions/page_object/test_main_page.py --language=en --browser_name=chrome
 pytest -s -q  solutions/page_object/test_main_page.py --language=es --browser_name=chrome
 pytest -s -q  solutions/page_object/test_main_page.py --language=fr --browser_name=chrome

дважды. Тесты проходят успешно.
Предлагаю убрать implicitly_wait

2024-09-26 03:31 UTC, Cliffart44 commented
@zinka22, а что даёт `-q` при запуске тестов?

2024-09-27 12:39 UTC, Cliffart44 requested changes

2024-09-27 12:39 UTC, Cliffart44 commented on solutions/page_object/test_product_page.py
> +    page = ProductPage(browser, base_shop_url)
Удалённая переменная ещё нужна?

2024-09-27 12:39 UTC, Cliffart44 commented on solutions/page_object/test_product_page.py
>  # Задание к негативным тестам содержится в tasks/task_negative_tests.md
В tasks/test_main_page.md тогда стоит прописать причину, почему `implicitly_wait` отсутствует (пункт на 141 строке).
И ещё такое ожидание нужно в solutions/pytest_folder/conftest.py?

2024-09-28 08:27 UTC, zinka22 commented
> @zinka22, а что даёт `-q` при запуске тестов?

Ничего особо не дает, покороче отчет, чтобы меньше листать в терминале.
Хотела сначала фото приложить, чтобы только список зеленых прогонов был. -q уменьшил, но не прямо до 12 строчек. Короткий отчет недоискала)

Читала вот [тут](https://habr.com/ru/articles/448782/#:~:text=%2Dq%2C%20%2D%2Dquiet%20%20%20%20%20%20%20%20%20%20%20decrease%20verbosity.)

2024-09-28 10:45 UTC, zinka22 commented on solutions/page_object/test_product_page.py
> +    page = ProductPage(browser, base_shop_url)
убрала, потеряла её. Искала по поиску в проекте, в документе и не находило её, нашла глазами.
Почитаю про поиск в pyCharm

2024-09-28 10:45 UTC, zinka22 commented on solutions/page_object/test_product_page.py
>  # Задание к негативным тестам содержится в tasks/task_negative_tests.md
не сделала 2ю часть вопроса, первую сделала.

2024-09-28 15:17 UTC, Cliffart44 commented on solutions/page_object/test_product_page.py
> +    page = ProductPage(browser, base_shop_url)
> не находило её

Скорее всего, была не та область поиска указана.

---
![image](https://github.com/user-attachments/assets/d2cbb08b-01be-4dc5-83c3-e6dc44c1ef7b)

2024-09-28 15:24 UTC, Cliffart44 commented on tasks/test_main_page.md
> +   upd: в задаче #60 Проанализировать возможность убрать implicitly_wait из задач с page_object
Исправить отступы, не удалять уже имеющиеся строки.

2024-09-28 15:27 UTC, Cliffart44 requested changes

2024-09-28 15:27 UTC, Cliffart44 commented on tasks/test_main_page.md
> +   upd: в задаче #60 Проанализировать возможность убрать implicitly_wait из задач с page_object
Исправить отступы, не удалять уже имеющиеся строки.
Также есть смысл смысл приложить полную ссылку, и если на задачу, то это 54, а не 60.

2024-09-29 16:54 UTC, zinka22 commented on solutions/page_object/test_product_page.py
>  # Задание к негативным тестам содержится в tasks/task_negative_tests.md
"...И ещё такое ожидание нужно в solutions/pytest_folder/conftest.py"

на память - нужно. Посмотрела файлы в #41 задаче, там еще и увеличивала ожидание с 10 до 15 секунд. Чтобы точно ответить, нужна задача #61

2024-09-29 17:11 UTC, zinka22 commented on tasks/test_main_page.md
> +   upd: в задаче #60 Проанализировать возможность убрать implicitly_wait из задач с page_object
ссылку добавила.

Что именно имеешь ввиду под "исправить отступы"? Просмотрела, что в test_main_page.md при вставке код есть пустая строка до и после кода. Добавила в 2х местах отступ после кода в [последнем коммите](https://github.com/zinka22/Selenium-cource/pull/60/commits/50fd51336c0c48db9d192b02f0318b49e5812f31)
Если не это имел ввиду, переделаю.

2024-09-30 07:46 UTC, Cliffart44 commented on tasks/test_main_page.md
> +   upd: в задаче #60 Проанализировать возможность убрать implicitly_wait из задач с page_object
## Было

![image](https://github.com/user-attachments/assets/6e179a57-576f-443a-b505-d9b1c1187e2f)

## Стало

![image](https://github.com/user-attachments/assets/5aea6b1f-0f85-4a20-a49f-a949abbb1be0)

2024-09-30 07:50 UTC, Cliffart44 requested changes

2024-09-30 07:50 UTC, Cliffart44 commented on tasks/test_main_page.md
>         `pytest -v --tb=line --language=en test_main_page.py`
```suggestion
    4. Убедитесь, что тест проходит, запустив его командой `pytest -v --tb=line --language=en test_main_page.py`.
```

2024-10-01 18:18 UTC, Cliffart44 approved these changes

2024-10-01 18:19 UTC, merged