Code duplication
zinka22/Selenium-cource pull request #8
Opened 2024-05-02 20:28 UTC by zinka22

Добавила вариант, как можно убрать дублирующийся код в файлах. Если ок, сделаю изменения в остальных аналогично этому

2024-05-03 09:37 UTC, Cliffart44 requested changes

2024-05-03 09:37 UTC, Cliffart44 commented on get_attribute.py
> +    helpers.wait_ten_seconds_and_close(browser) if browser else ...
С какой целью условная логика оставлена здесь?

2024-05-03 09:37 UTC, Cliffart44 commented on get_attribute.py
> +    browser = helpers.open_browser_page(link)
Если link используется в единственном месте, то нет особого смысла объявлять эту переменную.

2024-05-03 09:37 UTC, Cliffart44 commented on get_attribute.py
> +import helpers
```python
from selenium.webdriver.common.by import By

import helpers
```

2024-05-04 10:43 UTC, Cliffart44 requested changes
Уже можно задействовать везде две новые функции из helpers.

2024-05-04 10:43 UTC, Cliffart44 commented on helpers.py
>      time.sleep(10)
Если нет браузера, 10 секунд всё равно нужно ждать?

2024-05-04 18:57 UTC, Cliffart44 requested changes

2024-05-04 18:57 UTC, Cliffart44 commented on upload_file_from_pc/helpers.py
> +import time
Это дубликат основного helpers?

2024-05-04 18:57 UTC, Cliffart44 commented on helpers.py
>      time.sleep(10)
@zinka22, что насчёт такого?

```python
    if browser:
        time.sleep(10)
        browser.quit()
```

2024-05-05 14:10 UTC, Cliffart44 commented on upload_file_from_pc/helpers.py
> +import time
@zinka22, вопрос открыт: в PR, который призван убрать дублирование кода, мы привносим дублирование кода?

2024-05-05 14:22 UTC, Cliffart44 requested changes

2024-05-05 14:22 UTC, Cliffart44 commented on upload_file_from_pc.py
Почему этот файл удалён и как это связано с назначением этого PR?

2024-05-05 14:22 UTC, Cliffart44 commented on fill_the_form_with_XPath.py
> +    browser = helpers.open_browser_page(link)
Тут подход был лучше до изменений. Если есть желание дополнительно указать, что строка содержит ссылку, то можно сделать это так:
```python
    browser = helpers.open_browser_page(
        link="http://suninjuly.github.io/find_xpath_form"
    )
```

2024-05-05 14:22 UTC, Cliffart44 commented on radio_and_checkbox.py
> +    x = int(x_element.text)
Это изменение не относится к данному PR.

2024-05-07 18:27 UTC, zinka22 commented on helpers.py
>      time.sleep(10)
> Если нет браузера, 10 секунд всё равно нужно ждать?

Надо подумать. Ждать не нужно, но и быстрого решения нет.

2024-05-07 18:27 UTC, zinka22 commented on upload_file_from_pc/helpers.py
> +import time
да, иначе в подпапке не видел файла

2024-05-07 18:27 UTC, zinka22 commented on fill_the_form_with_XPath.py
> +    browser = helpers.open_browser_page(link)
везде сделала с ссылкой в скобках, переменную link убрала

2024-05-07 18:27 UTC, zinka22 commented on get_attribute.py
> +    browser = helpers.open_browser_page(link)
link убрала, везде ссылка в скобке, как предложил выше

`    browser = helpers.open_browser_page(
        link="https://suninjuly.github.io/selects1.html"
    )`

2024-05-07 18:27 UTC, zinka22 commented on radio_and_checkbox.py
> +    x = int(x_element.text)
убрала, поправлю отдельно

2024-05-07 18:27 UTC, zinka22 commented on upload_file_from_pc.py
файл удален, т.к. проведен неудачный rebase
это дубликат файла upload_file_from_pc.py из папки upload_file_from_pc

Явно не права. Как делать, если такое произошло и есть лишние файлы-дубликаты или предыдущие сохраненные файлы с таким же названием?

(тут была особенность, что файл == по названию с таким же файлом из папки, его только руками можно было удалить)

2024-05-07 18:32 UTC, zinka22 commented on upload_file_from_pc/helpers.py
> +import time
дубль helpers убрала

2024-05-07 18:33 UTC, zinka22 commented on get_attribute.py
> +    helpers.wait_ten_seconds_and_close(browser) if browser else ...
переставила ее в файл helpers, с конца файлов убрала

2024-05-07 18:33 UTC, zinka22 commented on get_attribute.py
> +import helpers
поменяла местами везде где нужно

2024-05-08 08:07 UTC, Cliffart44 commented on upload_file_from_pc.py
Насколько вижу, дубликат был внесён здесь https://github.com/zinka22/Selenium-cource/commit/e5231c27481fa91b2f8d4d3ff9ae11bc5204e91e, поэтому нельзя сказать, что где-то затем был сделан "неудачный rebase".

В таком случае удаление этого файла напрямую соотносится с этим Pull Request — другого способа теперь убрать лишнее не представляю (по-хорошему в https://github.com/zinka22/Selenium-cource/commit/e5231c27481fa91b2f8d4d3ff9ae11bc5204e91e и должно было бы быть удаление).

2024-05-08 08:24 UTC, Cliffart44 approved these changes

2024-05-08 08:24 UTC, merged

2024-05-08 09:49 UTC, zinka22 commented on upload_file_from_pc.py
поняла,  погуглила, почитаю вечером. 

1) тут править? Тут уже накрутила сильно. 
2) могу еще раз повторить содеянное и удалить правильно, чтобы попробовать

2024-05-08 10:58 UTC, Cliffart44 commented
PR слил, так что тут добавить уже нечего 🙂
Там сейчас весело в #9 будет с конфликтами — есть чем заняться 😉

ср, 8 мая 2024 г., 13:50 Natali ***@***.***>:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> On upload_file_from_pc.py
> <https://github.com/zinka22/Selenium-cource/pull/8#discussion_r1593756097>
> :
>
> поняла, погуглила, почитаю вечером.
>
>    1. тут править? Тут уже накрутила сильно.
>    2. могу еще раз повторить содеянное и удалить правильно, чтобы
>    попробовать
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/zinka22/Selenium-cource/pull/8#discussion_r1593756097>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APOZGJQIOT6H2UZYENLFKR3ZBHYM5AVCNFSM6AAAAABHEMNGWOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDANBVGE4TAOBXGI>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>

2024-05-08 10:58 UTC, Cliffart44 commented on upload_file_from_pc.py
PR слил, так что тут добавить уже нечего 🙂
Там сейчас весело в #9 будет с конфликтами — есть чем заняться 😉