Switch to.window
zinka22/Selenium-cource pull request #9
Opened 2024-05-04 20:10 UTC by zinka22

+1 задача из темы "Работа с окнами"

Следующий пул реквест будет не по задаче, а по теме (в теме 2-3 задачи). Код везде одинаковый, по одной задаче не вижу смысла (если что поправь)

2024-05-05 14:28 UTC, Cliffart44 commented
> +1 задача из темы "Работа с окнами"
> 
> Зацепилась от ветки code_duplication, т.к. нужен был актуальный helpers. Смотреть после #8. Если не правильно сделала, напиши.
> 
> Следующий пул реквест будет не по задаче, а по теме (в теме 2-3 задачи). Код везде одинаковый, по одной задаче не вижу смысла (если что поправь)

В целом гораздо удобнее таким образом оформлять новые задачи (отдельная ветка и затем Pull Request вместо прямых коммитов в `main`). По вопросу "сделать ветку не от главной" — само по себе это не проблема, но на рабочих проектах, скорее всего, создаст сложности. Здесь, в учебном проекте, можно и так.

2024-05-07 19:01 UTC, zinka22 commented
> > +1 задача из темы "Работа с окнами"
> > Зацепилась от ветки code_duplication, т.к. нужен был актуальный helpers. Смотреть после #8. Если не правильно сделала, напиши.
> > Следующий пул реквест будет не по задаче, а по теме (в теме 2-3 задачи). Код везде одинаковый, по одной задаче не вижу смысла (если что поправь)
> 
> В целом гораздо удобнее таким образом оформлять новые задачи (отдельная ветка и затем Pull Request вместо прямых коммитов в `main`). По вопросу "сделать ветку не от главной" — само по себе это не проблема, но на рабочих проектах, скорее всего, создаст сложности. Здесь, в учебном проекте, можно и так.

могу сделать squach and merge?убрала переменную, теперь тут как в остальных

2024-05-08 08:33 UTC, Cliffart44 requested changes
> могу сделать squach and merge?убрала переменную, теперь тут как в остальных

Для нормального ревью теперь эту ветку нужно [перебазировать](https://git-scm.com/book/ru/v2/%D0%92%D0%B5%D1%82%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B2-Git-%D0%9F%D0%B5%D1%80%D0%B5%D0%B1%D0%B0%D0%B7%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5) относительно main.

Откуда взялись конфликты? 
> Зацепилась от ветки code_duplication

2024-05-10 19:17 UTC, zinka22 commented
> Для нормального ревью теперь эту ветку нужно [перебазировать](https://git-scm.com/book/ru/v2/%D0%92%D0%B5%D1%82%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B2-Git-%D0%9F%D0%B5%D1%80%D0%B5%D0%B1%D0%B0%D0%B7%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5) относительно main.
> 

1) cделала rebase switch_to.window относительно main
2) сделала push switch_to.window в origin/switch_to.window
3) решила конфликты
Итого 1 измененный файл в этой задаче, 1 новый файл. 11 файлов - результат решения конфликтов с удаленной веткой. 

Не очень комфортная для понимания операция. Если нужно, попробую еще раз.

2024-05-11 09:36 UTC, Cliffart44 commented
>    Итого 1 измененный файл в этой задаче, 1 новый файл. 11 файлов - результат решения конфликтов с удаленной веткой.

В таком случае [здесь](https://github.com/zinka22/Selenium-cource/pull/9/files) два файла и должно быть. Сейчас же rebase не сделан надлежащим образом.

Нужно:
1. Перейти на ветку `switch_to.window`.
1. Выполнить `git rebase main`.
1. В процессе перебазирования решить конфликты.
1. Отправить изменения с флагом `-f` (⚠стоит [ознакомиться с рисками](https://git-scm.com/docs/git-push#Documentation/git-push.txt--f)).

В итоге в Pull Request останется [вот что](https://github.com/zinka22/Selenium-cource/compare/switch-branch-clone?expand=1#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L18) (ветка просто для демонстрации итога, ну и плюс как резервная копия 😉).

2024-05-12 15:21 UTC, zinka22 commented
> 
> Нужно:
> 
> 1. Перейти на ветку `switch_to.window`.
> 2. Выполнить `git rebase main`.
> 3. В процессе перебазирования решить конфликты.
> 4. Отправить изменения с флагом `-f` (⚠ стоит [ознакомиться с рисками](https://git-scm.com/docs/git-push#Documentation/git-push.txt--f)).
> 

не без проблем, но вроде справилась

2024-05-12 16:20 UTC, Cliffart44 commented
> не без проблем, но вроде справилась

Молодец! 🎉

По идее, уже заметила, что с методами из helpers разработка стала удобнее.

Пожалуй, здесь пока больше никаких доработок не требуется, но всё же не буду спешить сливать изменения в main: для полноты картины не хватает #10. Когда смогу сопоставить поставленную задачу и её реализацию, тогда и ревью будет исчерпывающим 👨‍💻

2024-05-16 07:26 UTC, Cliffart44 requested changes

2024-05-16 07:26 UTC, Cliffart44 commented on task_switch_to_window.md
В этом Pull Request не следует больше вносить никаких изменений — обновление документации к нему напрямую не относится. Здесь теперь стоит откатить изменения на момент https://github.com/zinka22/Selenium-cource/pull/9#issuecomment-2106305229.

2024-05-16 10:20 UTC, Cliffart44 approved these changes

2024-05-16 10:20 UTC, Cliffart44 commented on README.md
> +switch_to_window.py https://stepik.org/lesson/184253/step/6?unit=158843
Будет решено в #10.

2024-05-16 10:21 UTC, merged